### ISSUE TITLE
Overview of known issues

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/testable-projects-fcc#103]
@no-stack-dub-sack summarized the state of these testable projects as such:

# Some known issues:
- Materialize CSS package breaks the test suite completely (last I checked) - CSS rules are overridden and projects cannot be selected (this is where the UI we added is problematic. while less cool, and admittedly less user friendly, selecting the test suite with a hard coded variable was more reliable).
- Vue does not work with the tests suites at all as far as I know (this has been reported to me, I have not tried myself)
- Layout tests are problematic across the board - there are too many ways of centering things, making things sticky, etc. for these to always work. 
- CSS libraries cause all sorts of problems, if a user uses a className to achieve an effect that we test for, we won't detect it.
- Some CSS rules are not detectable when user is running tests in local dev environment rather than in codepen
- D3 tooltip tests cause lots of issues
- Scrolling libraries break tests that look for href anchors
- Cross browser issues like crazy (though this should be low priority in my opinion - perfect in Chrome and go from there)

**Comment by tchaffee** [comment]
Closing this because we have slightly changed our approach: rather than trying to support every single CSS package and every framework, we give Campers a recommended list of packages we support. We will look at adding the most popular frameworks like Vue and Angular, and even other major browsers. But beyond that we need to limit what we support in order to keep things maintainable.

**Comment by QuincyLarson** [comment]
@tchaffee Sounds good! Thanks for updating this with those details and closing it.
