### ISSUE TITLE
Pomodoro Clock tests not working properly

### ISSUE THREAD

**Issue by IngridAmaral** [freeCodeCamp/testable-projects-fcc#1038]
When testing appears : 13. When a session countdown reaches zero (NOTE: timer MUST reach 00:00), a new break countdown should begin, counting down from the value currently displayed in the id="break-length" element.

But it's working just like asked, when reaches Session 00:00 it changes to Break MM:SS, and other tests that depend on the same information are passing.

- Browser Name, Version: Chrome, newest
- Operating System: Linux
- Mobile, Desktop, or Tablet: Desktop

https://github.com/IngridAmaral/PomodoroClockReact
```



```

**Comment by ShunyaWatanabe** [comment]
Not working either.
My test cases don't look like they are proper, either :/

<img width="1440" alt="Screen Shot 2020-03-02 at 10 16 49 PM" src="https://user-images.githubusercontent.com/25846438/75705026-e8b12600-5cd3-11ea-9819-e7e6a465f16c.png">

**Comment by AryanJ-NYC** [comment]
I am getting the same failure and I believe I know where the bug lies (take this with a grain of salt as I am relatively new to the code of this test suite).

You can see [here](https://github.com/freeCodeCamp/testable-projects-fcc/blame/master/src/project-tests/pomodoro-clock-tests.js#L645) that async were added to wait for changes in the timer. However, with React relying on state for re-renders, the timer label ALSO takes time to re-render and its state should ALSO be `await`ed on.

My proposed fix is to `await` on time label changes (similar to how the tests `await` on timer changes).

**Comment by tbushman** [comment]
@IngridAmaral There were some changes to the test suite since this issue which may have resolved this issue. Thank you.

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
