### ISSUE TITLE
Wrong CDN link to run the tests

### ISSUE THREAD

**Issue by evasmolders** [freeCodeCamp/testable-projects-fcc#1050]
#### Issue Description

The wrong CDN link is provided for running the tests for the survey form challenge on https://www.freecodecamp.org/learn/responsive-web-design/responsive-web-design-projects/build-a-survey-form 

#### Browser Information

- Browser Name, Version: Chrome, newest (on 24/02/2020)
- Operating System: windows
- Mobile, Desktop, or Tablet: laptop

#### Your Code / Link to Your Pen

```
https://codepen.io/eefjekil/pen/vYBmGRd

```

#### Screenshot

![image](https://user-images.githubusercontent.com/22963091/75165691-0c4bfd80-5723-11ea-9cf5-4fe73eec0aaf.png)

**Comment by RandellDawson** [comment]
@evasmolders What makes you think it is the wrong CDN link?

**Comment by evasmolders** [comment]
In the screenshot I sent you can see that the tests it runs are the user
stories from the tribute page assignment.
I am not sure how to give more explanation?

**Comment by ojeytonwilliams** [comment]
Hey @evasmolders, it looks from your screenshot that the Tribute Page tests are selected.  If you click on that, you will see a drop down menu that includes Survey Form. Switching to that should mean all the tests pass.  Since it doesn't seem to be a problem with the CDN link, I'm closing this.

If you run into more problems, please reach out on the [forum](https://www.freecodecamp.org/forum/).  The community is great for this sort of thing!
