### ISSUE TITLE
Test #26 failing for Pomodoro Clock

### ISSUE THREAD

**Issue by tchaffee** [freeCodeCamp/testable-projects-fcc#110]
This test is failing on the [official code pen example for the Pomodoro Clock](https://codepen.io/freeCodeCamp/pen/XpKrrW).

#### Issue Description
Run the tests on the CodePen and test #26 will fail.

```
26. When a countdown reaches zero (NOTE: timer MUST reach 00:00), a sound (must be 200ms or longer) indicating that time is up should play. This should utilize an HTML5 <audio> tag and have a corresponding id="beep". ‣
Error: Timer has reached zero but, either there is not audio tag with ID 'beep' on the page, or it's not playing while it should.
    at https://gitcdn.link/cdn/freeCodeCamp/testable-projects-fcc/23e3e449972e54e21ca970d78000630b89e45697/build/bundle.js:19899:45
```

#### Browser Information

* Browser Name, Chromium Version 58.0.3029.110 
* Operating System: Ubuntu 16.04 (64-bit)
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen
Note that this is the official FCC example, so all tests should pass.

**Comment by tchaffee** [comment]
@no-stack-dub-sack The reason this test is failing is that the audio element is still playing and is just stopping playing from test #25 by the time test #26 ends. One of those timing issues that is hard to reproduce.

The only reason we are seeing this is because the setTimeout is hacked to make time "go faster". I wouldn't expect the audio to be playing for a full minute if the tests were done manually. However, it is also very subtle bug in the Pomodoro Clock Code. Ideally, the code should stop the beep audio when a user presses the 'reset' button?

I wonder how many students would do that on their own? Very few I would guess. So if that's important, we should add another test / requirement to the tests.

Another solution is to just add some code to test #26 to stop the audio if it is already playing from the previous test:

```
if (document.getElementById('beep')) {
    document.getElementById('beep').pause();
}
```

Or maybe better than that we could add it to the `before` and `after` functions.

Maybe @QuincyLarson wants to have a say in this? 

I'm leaning towards adding a test so that campers must stop the audio when the reset button is pressed. That's probably the most correct behavior.

**Comment by tchaffee** [comment]
Some more feedback: I [forked the Pomodoro Clock Codepen](https://codepen.io/tchaffee/pen/mwpBEq), changed the reset button to stop playing the audio, and all the tests pass now. If this is the path we want to follow, my next step would be to add a new test that ensures the audio stops playing when the user presses reset.

**Comment by tchaffee** [comment]
@no-stack-dub-sack @QuincyLarson Any feedback on this? If there is no strong opinion either way, I would like to go ahead and add a new test that requires the code to ensure the audio stops playing when the user presses the reset button. After that I would need some help understanding how to change the sample CodePen to get it to pass the new test.

**Comment by no-stack-dub-sack** [comment]
@tchaffee Hey Todd, sorry for missing this. Please feel free to message me on Gitter any time if I miss an issue, the list of issues I'm mentioned in is quite long from other projects so I sometimes miss them. Gitter is definitely a more reliable way to reach me if I don't respond in 1 or 2 days. Don't hesitate. 

This is interesting, because you haven't made a PR to address this yet, right? All tests are still passing on my end, and definitely were passing when the code was originally pushed. However, I can see what you're saying, I just don't see the same result, and haven't before. 

That said, it should pass on all platforms (I'm on Mac, and maybe this is the difference in Chrome?), and I have no strong opinion as to how this is addressed one way or the other.

**Comment by tchaffee** [comment]
@no-stack-dub-sack I have not made a PR yet, but I have code ready. I'm waiting until I understand what I need to do to fix the Pomodoro Clock example app. I don't know how to do that. I just ran the tests again, and that one is still failing. The timing for it to fail is very precise, so it's probably some combo of my OS, hardware, and browser version. If you can help me understand how I fix the Codepen example I can get moving on this.

**Comment by no-stack-dub-sack** [comment]
@tchaffee so you have the code to fix the example, you just need it to be changed on the official FCC Codepen example, right? I can do that for you. 

Can you just point me in the direction of the code that you changed so that I can take a look? (would be cool if there was a diff function in codepen)

**Comment by tchaffee** [comment]
Good idea about the diff in CodePen. I ended up copy pasting the source from both into kdiff3 (great visual diff tool once you learn it).  Below are the three lines you need and I've included some context. BTW, I used `ref` instead of `document.getElementBy` because the React docs recommend using it to access DOM elements that perform media playback.

```
  buzzer(_timer) {
    if (_timer === 0) {
      this.audioBeep.play();
    }
  }

....

  reset() {
    this.setState({
      brkLength: 5,
      seshLength: 25,
      timerState: 'stopped',
      timerType: 'Session',
      timer: 1500,
      intervalID: '',
      alarmColor: {color: 'white'}
    });
    this.state.intervalID && this.state.intervalID.cancel();
    this.audioBeep.pause();
  }

...

  <audio id="beep" preload="auto" 
    src="https://goo.gl/65cBl1"
    ref={(audio) => { this.audioBeep = audio; }}
  />
```

**Comment by no-stack-dub-sack** [comment]
@tchaffee yes! good call on the `ref`, I've since learned that but have not gone back to update things. the drum machine project could use that too now that I think about it.

Ok. All set, you should now see the changes reflected on the official Pen. 

So you're also going to add a new test that requires this behavior?

**Comment by tchaffee** [comment]
@no-stack-dub-sack Thanks for updating the pen. I am working on the new test now.

**Comment by tchaffee** [comment]
@no-stack-dub-sack I am preparing the PR now and will post it soon. But I there is one more line you should add to the CodePen, because I just figured out that `pause()` does exactly what it sounds like and when you invoke `play()` again it will start the audio where it left off. We also need to rewind:

```
  reset() {
    this.setState({
      brkLength: 5,
      seshLength: 25,
      timerState: 'stopped',
      timerType: 'Session',
      timer: 1500,
      intervalID: '',
      alarmColor: {color: 'white'}
    });
    this.state.intervalID && this.state.intervalID.cancel();
    this.audioBeep.pause();
    this.audioBeep.currentTime = 0;
  }
```

**Comment by no-stack-dub-sack** [comment]
@tchaffee all set!
