### ISSUE TITLE
I pasted in the same code from the example and my issue #7 will still not pass.

### ISSUE THREAD

**Issue by kristo413** [freeCodeCamp/testable-projects-fcc#1111]
#### Browser Information

- Browser Name, Version:
- Operating System:
- Mobile, Desktop, or Tablet:

#### Your Code / Link to Your Pen

```



```

**Comment by Sky020** [comment]
Hello there.

We need a lot more information, in order to be able to help you. I suggest you open a topic on the [forum](https://www.freecodecamp.org/forum), where we will be able to assist. Please provide the information of which project you are referring to, which code you are referring to, and a link to your CodePen or similar.

Cheers.

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
