### ISSUE TITLE
Media Queries not recognized by test suite

### ISSUE THREAD

**Issue by emireis** [freeCodeCamp/testable-projects-fcc#1132]
#### Issue Description

Just want to point out that I have multiple media queries in my project, however the test suite for "must include at least one media query" keeps coming back false. 

#### Browser Information

Google Chrome
- Google Chrome Version 81.0.4044.138
- Operating System: MacOS Catalina Version 10.15.4
- Desktop: MacBook Air

#### Your Code / Link to Your Pen

https://github.com/emireis/portfoliov2/blob/master/styles.css

```
#### Screenshot

<img width="1369" alt="Screen Shot 2020-05-15 at 10 04 34 PM" src="https://user-images.githubusercontent.com/50774264/82108947-30065a80-96f8-11ea-82e1-5f7299844f76.png">

**Comment by Sky020** [comment]
Hello there,

Please note: We are aware of an issue where the test suite does not pick-up on media queries, when run outside of CodePen.

It would help if you linked to where you are hosting your project? If you are not hosting it anywhere, I remind you that you will need to do this, in order to submit the project on freeCodeCamp.

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
