### ISSUE TITLE
I can't move on to the next project.

### ISSUE THREAD

**Issue by grasipacheco** [freeCodeCamp/testable-projects-fcc#1180]
#### Issue Description

I have finished the build a tribute page project and submitted and now when I try to move to the build a survey form still shows me the first project.

#### Browser Information

- Browser Name, Version:
- Operating System:
- Mobile, Desktop, or Tablet:

#### Your Code / Link to Your Pen

```



```

**Comment by Sky020** [comment]
Hello there,

Could you please describe in more detail what the issue is?
- Do you mean to say that once you click on the CodePen boilerplate for the _Build a Survey Form_ project, you are redirected to your previous CodePen project? Or, that you are redirected to the previous page on freecodecamp.org/learn?

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
