### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by sanqazz** [freeCodeCamp/testable-projects-fcc#1193]
#### Issue Description

Test # 6 for the Drum Machine tries to find "keyCode" (81 for "Q") when you use the "keydown" method, but when I try to use "keypress": event has "charCode" (113 for "Q") and music plays but the test fails

**Comment by nhcarrigan** [comment]
Hey there,

I recommend opening a post on the [forum](https://forum.freecodecamp.org) if you are still facing this issue. This will allow the community to help determine if the bug is related to the code you have written or the test suite itself. Additionally, please be sure to share a link to your live project so the community can effectively triage the error. 

As a side note, the `keypress` event is [deprecated, according to MDN](https://developer.mozilla.org/en-US/docs/Web/API/Document/keypress_event). 

I am going to close this issue. If, after further triage, it is determined that there is indeed a bug in the test suite, feel free to reopen this issue and provide the relevant information. 🙂
