### ISSUE TITLE
The code arbitrarily shows an error

### ISSUE THREAD

**Issue by Ammar-hub1994** [freeCodeCamp/testable-projects-fcc#1196]
#### Issue Description

I do not seem to be able to execute my code because of the "dropdown tag". The code seems to be having no error. Would you please look into the same.  

#### Browser Information

- Browser Name, Version: chrome
- Operating System: Windows 10
- Mobile, Desktop, or Tablet: desk

#### Your Code / Link to Your Pen

https://codepen.io/Ammarmohsen/pen/bGEJPbZ

```

#### Screenshot

![Capture](https://user-images.githubusercontent.com/66825983/88552273-f5dd0180-d034-11ea-9181-873f103574b9.PNG)

**Comment by nhcarrigan** [comment]
![image](https://user-images.githubusercontent.com/63889819/88552583-1d9e7c00-cfd9-11ea-9011-9ab075054fed.png)

Hello~!

Thank you for bringing this to our attention!

I believe the bug is because you have built your own dropdown, rather than using the HTML element. 🙂 
I will go ahead and close this issue as it appears not to be a bug in the test scripts. You are always welcome to post on our [forums](https://forum.freecodecamp.org) to seek help with debugging your code. 

Happy coding! 😁
