### ISSUE TITLE
Personal Portfolio Navbar link when clicked should take me to another part of the page. (FOOTER)

### ISSUE THREAD

**Issue by rcranker** [freeCodeCamp/testable-projects-fcc#1199]
#### Issue Description

Will not pass the test, but had no problem doing it this way through the lessons.

#### Browser Information

Version 84.0.4147.105 (Official Build) (64-bit)
Windows 10 Home
Alien Ware M17

#### Your Code / Link to Your Pen

```
<body>
  <navbar id="navbar" class="topnav">
    <a href="#">Home</a>
    <a href="#footer">Footer</a>
    <a href="#" id="profile-link">Contact</a>
    <a href="#">About</a>
  </navbar>
  <main>
    <section id="welcome-section">
      <h1>Welcome Section</h1>
  
    </section> <!--End of Welcome Section-->
    <section id="projects">
      <div class="project-tile">
        <h2 id="projectone">Project One</h2>
        <a href="www.projectone.com">Project One</a>
      </div> <!--End of Project-tile-->
    </section> <!--End of Projects-->
  </main>

    <footer id="footer">Created by Me</footer> 
 
</body>


```
#### Screenshot

![Portfolio](https://user-images.githubusercontent.com/69061534/89088796-25a74480-d368-11ea-81bd-17a8950c1109.PNG)

**Comment by nhcarrigan** [comment]
Hello~!

In general, it is recommended to open a topic on the [forum](https://forum.freecodecamp.org) for situations like this. That will allow the community to help triage the error. If it is determined that the error is indeed related to the test runners, *then* an issue should be opened. 

On a side note, it is best to share a link to your project rather than screenshots or code snippets. Live projects facilitate the debugging process and allow our community to better assist you. 

I am going to go ahead and close this issue. If it is determined that this is related to a bug in the test scripts, feel free to reopen the issue and provide the relevant information. 🙂
