### ISSUE TITLE
Include fcc eslint rules in this project.

### ISSUE THREAD

**Issue by tchaffee** [freeCodeCamp/testable-projects-fcc#120]
Should we and how can we best include [freeCodeCamp's JavaScript Style Guide](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/.eslintrc) in this project? 

If we make a copy, then we won't see any updates. But if we don't include it in this project we are missing ESLINT warnings that should be corrected.

@no-stack-dub-sack and @tbushman any ideas are appreciated.

**Comment by no-stack-dub-sack** [comment]
@tchaffee it may be a bit late to include these now, much of the code already written probably breaks tons of these rules. Making everything up to par could be a nightmare. Overall, I think enforcing style guidelines is good practice, but the FCC repo proper is a totally different animal because of the massive size of the codebase as well as the huge number of people contributing. 

Looking at this code, there are some things I'd def like to fix. I don't know what I was thinking with the spacing, for example. I was on a 4 spaces kick at the time, but I greatly prefer 2 now and I think it makes this code look pretty bad. 

That said, this is something that can be changed pretty easily manually. And given that there are only a few of us contributing, and that the number of contributors will likely never grow far beyond that, I think for now being vigilant with our PR reviews should be sufficient. If we want to play around with adding a few rules and seeing how it affects things, we can do that, just by installing the ES Lint package and writing an .eslintrc config file to configure the rules I believe. Either way, we would not need to be as stringent as FCC proper, and the config would have to be modified not to include React rules.

**Comment by tchaffee** [comment]
@no-stack-dub-sack I would be happy to start "fixing" the code to adhere to FCC style. As it is I am running out of issues to work on and have hours of free time that I could be spending improving the code.

In terms of maintaining a separate `.eslintrc`, that is actually my biggest concern. If there is a style change / addition at the FCC main app repo, how do we make sure changes are applied here as well? Wouldn't it make more sense to have a "company wide" `.eslintrc`? Perhaps in its own repo and all the projects use that as a git submodule? It doesn't make a lot of sense to me to have different standards for different projects, and in my experience what eventually happens is the style files get out of sync and different projects end up with different styles which is no fun. It should be easy to hop from one FCC project to another and be confident the style rules will be the same.

Concerning the React rules, t[hey can be easly turned off right in the source code](http://eslint.org/docs/user-guide/configuring#configuring-rules). ESLint is highly configurable, even at the fine-grained level of each source code file.

But if this is not a priority, then I am happy to shelve it for now and revisit later.

**Comment by no-stack-dub-sack** [comment]
@tchaffee If you're up for fixing it, by all means. But again, I just don't think this project will ever get the high level of exposure that FCC proper will and thus it is not mission critical for now, though I agree at some point much can be improved.

Even if there aren't any specific issues to address right now though, my preference (if you are willing to spend the time) would be to have you try to deliberately break the tests in as many ways as possible (by creating new projects against the tests or by modifying existing ones - though the first option is more realistic). We could try using other libraries too to see how they interact with the test suite. For instance, the Materialize thing - I wonder if we can find a way around this or if people just won't be able to use materialize?

Whether we discover them or not, other issues will undoubtedly come up. So I think that would be more valuable at this point since this project WILL be a part of the new FCC roll out (even if many people aren't contributing to it) and ideally there will be as few problems with it as possible when we release. So that would be my vote - this is just something I haven't had the time to do much of myself lately, but I think its still high priority.

In terms of the styles though - I think switching the spacing to FCC spacing is fine, like you said, React rules can be turned off if we go that route, and at the time I wrote this, I hadn't yet discovered template literals to break strings up on to multiple lines when they are getting too long. Using these would be far preferred to the silly string concatenation the project currently uses.

**Comment by tchaffee** [comment]
> my preference (if you are willing to spend the time) would be to have you try to deliberately break the tests in as many ways as possible

I'm fine working on whatever the priority is. As far as breaking the tests, are there a few camper projects I should be focusing on where you feel like the tests would be easy to break and that need more attention? I'm guessing the Tribute page for example doesn't need the most attention.

Could you give me a code example of how you would break up a string with a template literal? If I can see what you have in mind I can follow that style?

**Comment by no-stack-dub-sack** [comment]
@tchaffee I think we answered your first question in the meeting today, and as for your second, I think I may work on a PR to bring everything to 2 spaces instead of 4 (which conforms with FCC style guidelines) and breaking up the long strings better, just to get us started on this. 

But what I mean is:

```js
it(`1. I can see a <main> element with a corresponding id="main-doc",
    which contains the page\'s main content (technical documentation).`, function() {...});
```

Using back ticks instead of single or double quotes will allow the strings to be broken up over multiple lines without having to concatenate them.

**Comment by no-stack-dub-sack** [comment]
@tchaffee it also looks like FCC enforces a max line length of 80 chars. If we were do to this, a lot of the tests would end up looking like this:

![image](https://user-images.githubusercontent.com/18563015/27757102-9fa546f8-5dcb-11e7-8866-ddc5e2b934c6.png)

What do you think? I know I said we shouldn't prioritize this, but the more I look through, the more it's bothering me :smile:

**Comment by tchaffee** [comment]
@no-stack-dub-sack Concerning your comment about the backticks, the only problem with this:

```
it(`1. I can see a <main> element with a corresponding id="main-doc",
    which contains the page\'s main content (technical documentation).`
```

Is that the backticks include newline characters and whitespace. So you'd get the following string. Note the newline and the white space:

```
1. I can see a <main> element with a corresponding id="main-doc",
    which contains the page's main content (technical documentation).
```

Not sure if that's what you are looking for? You can escape the newline with the backslash, but I haven't ever found a way of getting rid of the white space, and without the newline, the white space of four space would definitely look wrong. If the newline actually will look ok in the test UI, then this could work.

**Comment by tchaffee** [comment]
> FCC enforces a max line length of 80 chars.

I think narrow code is easier to read. Like reading a book (usually max 60 columns!). BUT, writing tests are the one case where the 80 character max is sometimes a pain because you have to break the narrative text over so many lines and it become harder to maintain when you need to add one word to a line.

I don't have a great answer for this. Long strings in javascript (and many other languages) are just a pain to maintain. Per the [MDN docs on long strings](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String#Long_literal_strings), they suggest just using the `+` like we have been doing, or backslashes. Backslashes have the same problem as backticks: whitespace at the beginning of the line are included as part of the string.

If I had to decide on this, I would say just break the strings up onto many lines using the `+` sign and when we have to edit the strings we just have to deal with it. Backticks could be useful where we are inserting data into the string, which so far I haven't seen.

**Comment by jnmorse** [comment]
I don't know if this is something still being thought about. But since I noticed this and was curious about setting up my own eslint config that I could import. I tried it with the fcc rules. My first attempt generated errors in the freeCodeCamp code but turned out that was cause I was using different package version.

If I updated the eslint version to 4.7.2 then it runs and still produces errors, but this time the errors where linting rules that were broken. You can see them in the screenshots I'll include.

The repo is here: https://github.com/jnmorse/eslint-config-fcc

### Screenshots

*freeCodeCamp*
![freecodecamp-linting-results](https://user-images.githubusercontent.com/1467889/31015441-1eb2ff9e-a4ee-11e7-9445-34a5a28c5690.png)

*testable-projects-fcc*
![testable-linting-results](https://user-images.githubusercontent.com/1467889/31015449-2617415a-a4ee-11e7-9663-0a211ee00e12.png)

**Comment by tbushman** [comment]
@jnmorse Yes, this is a coordination in progress. Please see issue #214.

**Comment by jnmorse** [comment]
@tbushman I was refering more to the importing of the FCC rules.  The repo I linked contains all the rules as they are defined in the freeCodeCamp project, and the screenshots where just to show that it was working.  Long as the installed version of eslint was 4.7.2 and not 3.x.x  Course requires that the config repo is maintaned and kept up to date.

The easiest way to keep it maintaned of course is fcc creates a simular package and use that package in place of having the rules defined directly in the freeCodeCamp project. There may be a need to have certain rules defined only for certain projects, but those can be defined in the .eslintrc file of the project using it.

With the repo I created, I can install the fcc rules with `npm i -D eslint jnmorse/eslint-config-fcc'.

Then in .eslintrc or .eslintrc.json I just need to put

```json
{
  "extends": "fcc"
}
```

and running the lint scripts, the existing one in the package.json file for freeCodeCamp, and one I added on my local copy of testable-projects-fcc, which was just `"lint": "eslint ."`, resulted in the two screenshots in my previous comment.

**Comment by tbushman** [comment]
@jnmorse OK. A good strategy. @tchaffee will want to look into this.

**Comment by tchaffee** [comment]
@jnmorse We are already each locally using the eslint rules from the main FCC project and file by file we are getting rid of the warnings. If you can contact me on Skype (tchaffee2006), I'll give you a link to the spreadsheet that is tracking progress. There is really only one small change left that I'll try to get to in the next few days. Once that's done, we will add the eslint rules to the project, and then we will also make sure the Continuous Integration build checks the eslint rules for any violation.

**Comment by jnmorse** [comment]
@tchaffee my comments were mainly directed at this

> In terms of maintaining a separate .eslintrc, that is actually my biggest concern. If there is a style change/addition at the FCC main app repo, how do we make sure changes are applied here as well? 

If FCC moved to having an importable eslint config, then it should be easy to make sure that the rules being used here are always the same as the ones being used elsewhere.  It seems to be fairly easy to make the config to be imported.

If campers wanted they could also import those rules into their own projects that way without copying the .eslintrc from the freeCodeCamp repo.

The repo I linked earlier https://github.com/jnmorse/eslint-config-fcc is currently using a similar setup as the eslint-config-airbnb, but only including the fcc rules, though I did add a restricted globals rule which may or not be needed.

I didn't really like the tool eslint-find-rules they were using for finding unused rules though and started working on my own [eslint-rule-finder](https://github.com/jnmorse/eslint-rule-finder) which can save unused rules to a markdown file, separated by category which should help with maintance.

I don't mind helping with maintaining a config package if desired. The ultimate approach to this, of course, is in your hands, I just thought I'd mention it as a suggestion.

**Comment by tchaffee** [comment]
@jnmorse Thanks for the explanation. It all makes more sense now. I like the idea of importing the FCC eslint config, so it would be great if you could make a PR for that specifically with no additional functionality other than importing. 

Concerning the eslint-find-rules, that seems like extra functionality? It's not 100% clear to me what it does, but unless it's needed for importing the FCC eslint config, I would open a separate issue for that as an enhancement suggestion so we can discuss the pros on cons.
