### ISSUE TITLE
Lazyload bag test iframe

### ISSUE THREAD

**Issue by GurovDmitriy** [freeCodeCamp/testable-projects-fcc#1204]
#### Issue Description

if iframe data-src=""  id="video" class="lazyload" - test no success complete...

#### Browser Information

- Browser Name, Version:
- Operating System:
- Mobile, Desktop, or Tablet:

#### Your Code / Link to Your Pen

```



```

**Comment by Sky020** [comment]
Hello there,

As this issue does not contain enough information for us to debug or help, it is invalid. Therefore, I am closing this issue.

If you accidentally opened this, then there is not need to do anything. However, if you still are encountering an issue, then please edit your description to include useful information such as:
- What you are trying to accomplish
- What the expected behaviour is
- What the actual behaviour is
- What tools you are using (OS specific information)
- Any relevant links (CodePen, User profile...)

Once that is updated, we can reopen this issue. Thank you.
