### ISSUE TITLE
Product Landing Page URL trouble

### ISSUE THREAD

**Issue by dtiffany** [freeCodeCamp/testable-projects-fcc#1210]
#### Issue Description

I have a submit button for the email input section of the webpage. To send the info to the right place, I placed an action attribute in the form element and set it = to the URL given for the assignment. But whenever I test the button by clicking on it, the page crashes. I have tested other URLs in place of the one given, and they work just fine. This leads me to believe there's something wrong with the provided link.
#### Browser Information

- Browser Name, Version: Chrome, Version 84.0.4147.105
- Operating System: HTML
- Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```

https://codepen.io/dtiffany/pen/PoNzjEx?editors=1010

```

**Comment by Alendia** [comment]
I met the same problem. After clicking the submit button, the codepen responsed " freecodecamp.org refuse the request". I checked this URL in the browser, but it directed to a user profile page.

**Comment by Sky020** [comment]
Hello there (@dtiffany and @Alendia ),

The error is due to CodePen, and, from what I can see, will not be fixed. This is the full error:
> Refused to display `'https://www.freecodecamp.org/email-submit?'` in a frame because it set 'X-Frame-Options' to 'sameorigin'.

It would involve changing the options for `freecodecamp.org`, which could open campers up to potential fraud.

Also, there would be no point in allowing such an action to take place, because  `'https://www.freecodecamp.org/email-submit?'` is not a link to a script which handles emails.

There is no need to test the functionality, because the link is not functional. Provided the `form` has the URL as the value for the `action` attribute, the test will pass.

As such, I am closing this issue.
