### ISSUE TITLE
getting an error on product landing page #landing test. it says the navbar should always be at the top of the page. the navbar is at the top of my page but i am still receiving the error.

### ISSUE THREAD

**Issue by poplegogdev** [freeCodeCamp/testable-projects-fcc#1219]
#### Browser Information

- Browser Name, Version:
- Operating System:
- Mobile, Desktop, or Tablet:

#### Your Code / Link to Your Pen

```
https://codepen.io/poplegogdev/pen/MWWpeOx


```

**Comment by Sky020** [comment]
Hello there,

I recommend you open a topic on the [forum](https://forum.freecodecamp.org) about this, because it does not have to do with the source code or test-suite.

When opening a topic on the forum, be sure to give your post a descriptive title, and include the question in the body of the post, as well as a link to your project.

As such, I am closing this issue. Thank you
