### ISSUE TITLE
FCC Personal Portfolio - Can't get Layout #3 test to pass regarding navbar and viewport

### ISSUE THREAD

**Issue by bds67** [freeCodeCamp/testable-projects-fcc#1220]
I keep running the test but still can't get it to pass even though I have top and left settings at zero. Everything looks fine as far as navbar positioning and location is fixed.

3. The navbar should always be at the top of the viewport.
Navbar should be at the top of the viewport even after scrolling : expected -500 to be close to 0 +/- 15
AssertionError: Navbar should be at the top of the viewport even after scrolling : expected -500 to be close to 0 +/- 15
    at Proxy.T (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:549:12413)
    at Proxy.l (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:431:130)
    at Function.n.approximately (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:574:8045)
    at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:657:126116
    at l (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:657:98461)
    at Generator._invoke (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:657:98214)
    at Generator.forEach.e.<computed> [as next] (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:657:98818)
    at r (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:1:1054)
    at i (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:1:1265)

#### Browser Information

- Browser Name, Version: Version 85.0.4183.83 (Official Build) (64-bit)
- Operating System: Windows 10 Home 64bit
- Mobile, Desktop, or Tablet: HP Laptop

#### https://codepen.io/bds67/pen/MWyEqLX

<script src="https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js"></script>
<!DOCType html>
<html>

    <nav id="navbar">
      <div class="nav">
        <div class="menu">
          <a href="#welcome-section" id="home">Home</a>
          <a href="https://codepen.io/bds67" id="profile-link" target="_blank">About</a>
          <a href="#projects" id="#portfolio">My Work</a>
          <a href="#contact" id="contact-me">Contact</a>
        </div>
      </div>
  </nav>

      <section id="welcome-section" class="welcome-section">
        <h1>Hello, I'm Baltasar</h1><br>
        <p>A Web Designer based in Spring, Texas</p>
      </section>

        <section id="projects" class="project-display">
          <h2>Here is some of my work</h2>

        </section>
  <section id="contact" class="contact-section"></section>

</html>

@import url('https://fonts.googleapis.com/css2?family=Merienda+One&family=Quicksand&display=swap');
body {
  margin: 0;
  padding: 0;
  font-family: 'Quicksand', sans-serif;
  background-image: url("https://wallpaperboat.com/wp-content/uploads/2019/10/free-website-background-02-728x410.jpg");
  background-color: #cccccc;  
  background-repeat: no-repeat;
  background-size: cover;
  position: relative;
}
.welcome-section h1{
  font-family: 'Merienda One', cursive;
  color: #db4237;
  font-size: 50px;
  text-align: right;
  width: 95vw;
  margin-top: 240px;
  position: absolute;
  padding-left: 0;
}
.welcome-section p{
  color: black;
  text-align: right;
  width: 95vw;
  margin-top: 330px;
  position: absolute;
  font-size: 4vw;
}
.nav{
  width: 100%;
  background: #0979e0;
  position: fixed;
  text-align: center;
  top: 0;
  left: 0;
  z-index: 500;
}
.menu a{
  display: inline-block;
  padding:20px;
  color: #fff;
  text-decoration: none;
  font-size: 5vw;
}
.menu a:hover{
  background: #6cb0f0;
  color: #fff;
  transition-duration: 0.5s
}
.welcome-section{
  width: 100vw;
  height: 100vh;
}
.project-display{
  background: #f7a7a1;
  text-align: center;
  width: 100vw;
  height: 100vh;
}
.project-display h2{
  padding-top: 140px;
}
@media screen and (min-width: 480px) {
  body {
    background-color: #9fc6d1;
  }
}

**Comment by Sky020** [comment]
Hello there,

In general, I recommend opening a topic on the [forum](https://forum.freecodecamp.org) for a problem like this. In your case, the issue is the HTML structure:
```
    <nav id="navbar">
      <div class="nav">
        <div class="menu">
```
There is only one element within each of these, so it does not make sense to have so many layers. I suggest you move `.nav` and `.menu` to within `#navbar`, and remove the `div` elements.

---

Some things to note when using CodePen:
1) CodePen does not expect any content outside the `body` tags.
2) All `meta`, `link`, and `script` information must be put in the :gear: settings section of the HTML editor.
3) You do not need to/cannot link the _CSS_ in your HTML, if you place the CSS in the appropriate section.
4) If your project uses React, use the Babel preprocessor, and link the CDN in the appropriate :gear: section.
5) The editors offer the ability to format and analyze your code, providing useful information about forgotten closing tags _etc._

If you are still confused with how to use CodePen, please read the official [documentation](https://blog.codepen.io/documentation/).

Hope this helps

**Comment by bds67** [comment]
Thanks so much. That did the trick. I guess I was trying to compartmentalize everything on it's own but instead of making it easier, it complicated it all.
