### ISSUE TITLE
User Story #11: Within the form, there is a submit input with a corresponding id="submit"

### ISSUE THREAD

**Issue by JPaladini75** [freeCodeCamp/testable-projects-fcc#1223]
#### Browser Information

- Browser Name, Version:
- Operating System:
- Mobile, Desktop, or Tablet:

#### Your Code / Link to Your Pen

<form id="form" action="https://www.freecodecamp.com/email-submit">
  
  <h1 class="title">Tusla Tools</h1>
  
  <input id="email"
         type="email"
         name="email" 
         placeholder="Enter your email address"
         button-type="submit">
  
  <input id="submit" 
              type="button"
              value="Select"
                        </form>
                        <br>
```



```

**Comment by Sky020** [comment]
Hello there,

As this issue does not contain enough information for us to debug or help, it is invalid. Therefore, I am closing this issue.

If you accidentally opened this, then there is not need to do anything. However, if you still are encountering an issue, then please edit your description to include useful information such as:

- What you are trying to accomplish
- What the expected behaviour is
- What the actual behaviour is
- What tools you are using (OS specific information)
- Any relevant links (CodePen, User profile...)

Once that is updated, we can reopen this issue. Thank you.
