### ISSUE TITLE
N

### ISSUE THREAD

**Issue by johnpyp** [freeCodeCamp/testable-projects-fcc#134]
#### Issue Description

Centered element not registered as centered on Quote Generator project.

Centered via Boostrap 3.3.7 col-xs-4 col-xs-offset-4

https://codepen.io/johnpyp/full/NgoeZX/

Fork that to reproduce.

#### Browser Information

* Browser Name, Version: Chrome 59.0.3071.115
* Operating System: Windows 7 64-bit
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```
 
 https://codepen.io/johnpyp/full/NgoeZX/
 
```

#### Screenshot

![image](https://user-images.githubusercontent.com/20625636/28183123-47a768c6-67dc-11e7-998c-8bafc14b817d.png)

**Comment by tchaffee** [comment]
@johnpyp Thanks for reporting this and we will look into it as soon as we can.

**Comment by marigerr** [comment]
I can take a look at this! (since I've just been working on quote-machine)

**Comment by marigerr** [comment]
It looks like the problem is due to `offsetLeft ` property that is currently used which gets the offset only in relation to the parent element.   It fails in the linked pen since Bootstraps offset class was used and thus the element is offset within the parent element.   But this imo is a valid way to center an element and should be accepted.  

Current left alignment Layout Test:  

```
const centeredElement = document.getElementById(elName);
const actualSideGap = centeredElement.offsetLeft;
```
I've started testing instead using [.getBoundingClientRect();](https://developer.mozilla.org/en/docs/Web/API/Element/getBoundingClientRect) which returns position of element relative to the viewport.  So this will allow Bootstrap offset class to be used.  It tests well on both Codepen and locally for several pens including the official fcc example project.   
```
const boundElementRect = centeredElement.getBoundingClientRect();
const leftMargin = boundElementRect.left;
const rightMargin = window.innerWidth - boundElementRect.right;
return Math.abs(leftMargin - rightMargin) < 10;
```
I'll test further and then submit a PR.

**Comment by tchaffee** [comment]
@marigerr I agree this is a valid way to center an element. Your approach sounds good since it is checking the actual physical location of the element on the page. Looking forward to seeing a PR.
