### ISSUE TITLE
Random Quote Machine failing test

### ISSUE THREAD

**Issue by DennisEnt** [freeCodeCamp/testable-projects-fcc#140]
#### Browser Information

* Browser Name, Version: Chrome, Version 59.0.3071.115
* Operating System: macOS Sierra
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```
 For the Random Quote Machine Project I keep failing the last test: 

10. I can tweet the current quote by clicking on the #tweet-quote element. This element should use the "twitter.com/intent/tweet" path to tweet the current quote 
 
AssertionError: #tweet-quote element must have an href attribute : expected false to be truthy```

This is the code I've used for the tweet button:

 <a class="nothing"><button class="btn" id="tweet-quote"><i class="fa fa-twitter" aria-hidden="true"></i></button></a>

I have tried giving the a element a href attribute but I still fail the test.
#### Screenshot
<!-- Add a screenshot of your issue -->

**Comment by marigerr** [comment]
Hi, I have a [pending fix/pull-request](https://github.com/freeCodeCamp/testable-projects-fcc/pull/132/files) for this test as I had a similar problem.  The fix will hopefully make the requirement clearer that an \<a\> element with an id of "tweet-quote" is required and the href as well.   
The test fails your code because the it is unsuccessfully checking for an href on the element with the id="tweet-quote" which is the inner <button> element.

**Comment by DennisEnt** [comment]
Why not remove the href requirement for this? 
I've used an event listener not a href for this:


document.getElementById("tweet-quote").addEventListener("click", function () {
--
  | window.open(`https://twitter.com/intent/tweet?text=+${quote}-${author}`);
  | });

**Comment by marigerr** [comment]
I'm new to contributing to this repo, but from what I've read I believe the goal is to make the challenge descriptions/requirements very specific and then narrowly test for those requirements.  Otherwise it would be difficult to test for all the different ways projects could be built.   

And because it's in beta, the process of fine-tuning the challenge descriptions and the test is still a work in process.  

I also used a click handler in my original code that led to me opening [my issue](https://github.com/freeCodeCamp/testable-projects-fcc/issues/128) 

I had wondered what is the best practice and tried to research it a little and am thinking now that an anchor element is preferred to use vs a button to open a new page like twitter.

Some random blogs on the subject 
https://davidwalsh.name/html5-buttons
https://css-tricks.com/use-button-element/

**Comment by tchaffee** [comment]
@DennisEnt What @marigerr said is right. While we would like to support all possible solutions, it would make the automated tests huge, and very fragile. Someone would always be able to find a new way of coding a project that breaks the tests. We are in the process of making sure the tests are more specific about how each project should be built. Thanks for reporting this, because it helps us refine the tests. If you change your code to use an anchor element, the tests should pass. Please let us know.

**Comment by tchaffee** [comment]
Fixed with https://github.com/freeCodeCamp/testable-projects-fcc/pull/132, which makes it clearer that campers must use an anchor element along with a a valid `href` attribute.
