### ISSUE TITLE
Product Landing Page example

### ISSUE THREAD

**Issue by MarcBradbury** [freeCodeCamp/testable-projects-fcc#150]
#### Issue Description
despite attempting to view the pen example for the Product Landing Page each is met with the same issue where the navbar is expanded to cover most of the screen.
(this is referring to the beta version)

#### Browser Information

* Browser Name, Version:  Opera, 46.0.2597.57/ Chrome, Version 59.0.3071.115 (Official Build) (64-bit) /Firefox Dev Edition, newest
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen
https://codepen.io/freeCodeCamp/full/RKRbwL/ (not my pen, but the example pen given)

 
#### Screenshot
http://imgur.com/a/jVYa9

**Comment by tbushman** [comment]
Thanks @MarcBradbury. It looks like the problem is coming from the shopify logo. It is has a rather large transparent margin. I tried out shopify logo maker, and the logo came with a smaller margin. @no-stack-dub-sack, @QuincyLarson, just wondering if this logo was post-processed.

**Comment by tchaffee** [comment]
@tbushman @QuincyLarson @no-stack-dub-sack I recommend against using dynamically generated images in both the example projects and camper implementations. As we've seen here, any changes to the Shopify code could affect / break this project. The Shopify service could also go down temporarily, or permanently.

I would guess we are doing this because CodePen doesn't allow storing assets? Is there a better work-around than this? Maybe hosting the image(s) in a github project which we could access via rawgit CDN? I'm open to other ideas.

**Comment by QuincyLarson** [comment]
@tchaffee Yes - that's my understanding. Some sites like Imgur have blocked CodePen due to the fact that they keep pulling images on each refresh.

Hotlinking to images is unfortunate but the only reliable way around it is to host images yourself (on S3 or your own web server). I think we could make a note about this in the challenge, but it would be overkill to go in and walk them through creating an AWS account to put images in S3.

**Comment by tchaffee** [comment]
@QuincyLarson Making a note of S3, github, and your own web server as possible options in the challenge would be good enough IMO.

**Comment by marigerr** [comment]
I started trying out [Cloudinary.com](http://cloudinary.com/) as I've seen others recommend it.   I use it in one of my pens and so far so good.   They don't seem to limit views/downloads.  [Are Cloudinary APIs limited?](https://support.cloudinary.com/hc/en-us/articles/202520892-Are-Cloudinary-APIs-limited-)

**Comment by tchaffee** [comment]
@QuincyLarson The more important thing though is getting the example CodePen fixed. Anyone know who wrote it and if we can have them take a look?

**Comment by QuincyLarson** [comment]
@tchaffee yes - if you can tell me exactly what code needs to be replaced, I can log into CodePen and fix it :)

**Comment by tchaffee** [comment]
@QuincyLarson I am away for the next week most likely without access to a computer. Maybe someone else here like @tbushman or @marigerr can let you know? I think it's just a matter of creating an "normal" size image for the page and then hosting it somewhere.

**Comment by tbushman** [comment]
@QuincyLarson The image url is in line 4 of the html for Product Landing Page: https://codepen.io/freeCodeCamp/pen/RKRbwL

**Comment by marigerr** [comment]
@tbushman @QuincyLarson   I can find and download a new logo on possibly flaticon and load it up to Cloudinary, if you think that might be a good solution.

**Comment by tbushman** [comment]
@marigerr Thanks. You can use the png I shared. It is the exact logo without the added transparent margin mentioned. 
Here is the url please for reference: 
https://cdn.shopify.com/tools/logo-maker/show/aXVZQVUxQzVaRWUvL2ErVlhNajhydz09LS10dEJ3RkFOVzIzaXhMdHBJT2RvMWVRPT0=--55e0484dc3ed246afecaba4ab16c8816c438ea00_1000x.svg.png

**Comment by marigerr** [comment]
Oh great so don't need to look for new image.  I actually just realized it might be better for FCC to host on its own cloudinary account (or other platform) instead of mine, for future maintainability.

**Comment by QuincyLarson** [comment]
Thanks for your patience everyone! I've put this image up on s3 and updated the example app.
