### ISSUE TITLE
Markdown Project Tests Broken in React 15.6.1

### ISSUE THREAD

**Issue by jnmorse** [freeCodeCamp/testable-projects-fcc#222]
#### Issue Description

When using react and react-dom 15.6.1 the input event does not trigger with onChange. if you have onInput on the textarea then it works, but React will then complain that you have a value but no onChange defined.

I have yet to find an event that will trigger the onChange in React.

I first noticed while debating on creating an issue about testing for if the preview is an iframe, and attempting to write the tests in a way that would work.

#### Browser Information

* Browser Name, Version: Chrome, Version 61.0.3163.100 (Official Build) (64-bit)
* Operating System: Ubuntu 16.04
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

[FCC Example Codepen Fork](https://codepen.io/jnmorse/pen/RLoKdJ)
[My Markdown Project](https://codepen.io/jnmorse/pen/bExXqm)

#### Screenshot

![markdown-project-15 6 1](https://user-images.githubusercontent.com/1467889/30779752-28c1a60a-a0c7-11e7-90e9-9208e673d823.png)

**Comment by tbushman** [comment]
@jnmorse Thanks for reporting this. I'll keep looking into this, and in the meantime, your pen will pass with react and react-dom versions 15.5.0.

**Comment by jnmorse** [comment]
@tbushman apparently I goofed when I posted this last night. I pasted the same URL for my project in the second link. I've updated it now.

**Comment by tbushman** [comment]
@jnmorse OK. I have reproduced the error on both the official fCC codepen and yours when using the latest version of react. Thanks for reporting this.  
@QuincyLarson @no-stack-dub-sack Please see this discussion, where the solution was to set `<form autoComplete=off>`: https://github.com/facebook/react/issues/10657

The react team is recommending the use of `componentWillReceiveProps` to trigger events, instead of `el.dispatchEvent()`. Please see this thread: https://github.com/facebook/react/issues/8971 and this pen: https://codepen.io/pudgereyem/live/OWBrdv?editors=0010.  
  
This would mean, similar to the nextTick issue with the vue markdown example, either recommending `componentWillReceiveProps` event triggering in camper projects or mounting the project's component in the test suite somehow (?).

**Comment by tbushman** [comment]
@jnmorse Thanks for alerting to the textarea / input event triggering issue with the latest version of react. I've forked your Codepen to test against PR #223 and am trying to track what is causing the tests to fail, because your code works. I'm blocking the PR for now.

**Comment by tbushman** [comment]
@jnmorse I believe that it might be either the method of mounting / rendering the iframe (within the Codepen iframe) or update prop conflicting with onChange in the Editor component that cause the tests not to pass. I haven't narrowed it down, but I made some modifications that passed the tests. Here is the diff between code after making some changes: http://www.diff-online.com/view/59c9e0a3435d0

**Comment by jnmorse** [comment]
@tbushman I pulled in your changes and used it to add in some changes of my own. Now I don't know if the test should allow for an iframe output or not, but I worked out a way to get the tests to pass at least with my setup.  If you load my pen again and click run tests it will use my changes and all the tests pass.

https://github.com/jnmorse/testable-projects-fcc/commit/73e1bf0c997980a4e6b1409af3cad34107600ddf

**Comment by tbushman** [comment]
@jnmorse Is there an advantage to rendering the preview element in an iframe in this project? It almost seems to complicate things unnecessarily.  
I'll check the pen later. Looks like we broke Codepen. ;)

**Comment by jnmorse** [comment]
@tbushman The advantage, at least to me, as it allowed me to use highlight.js, its stylesheet, and one that is suppose to help make the output a bit more like Github without my own styles conflicting.

**Comment by tbushman** [comment]
@jnmorse OK, I will create an issue regarding a method for importing react components for testing because this is not the only case where the parts of projects that need testing are virtual at the moment of testing. In your case, simply giving the inner div an id='preview' didn't work on my end. I could not make it available for JS query. Unless you haven't tried that, you should submit a PR and let the discussion start. We should keep the fix I submitted separated. Please submit for React <=15.5, without `src/project-tests/markdown-previewer-tests.js`, function `withValue` and `defineProperty()`. Thanks!

**Comment by jnmorse** [comment]
@tbushman Okay submitted pull request #225 which contains well a revised method of what I previously mentioned for grabbing the iframe content in my pen. As I mentioned in the pull request I did sneak another change in there to the option links tests, since I thought it was a bit misleading that it pass if there were other problems and no links were found.

I can also make that a separate pull request if you wish, or remove it if you liked the way it was before, just let me know.

**Comment by tbushman** [comment]
@jnmorse OK, Thanks! I will wait until I can get another reviewer before any merges. Are you able to request a reviewer from your screen? 
Also, the package-lock.json ... It's recommended that we check that in, but we may need yet another PR to initiate that, is my guess. We've been omitting it. Maybe bad.

**Comment by jnmorse** [comment]
@tbushman Okay I have re-pushed those two pull requests removing the things mentioned.
