### ISSUE TITLE
[Proposal] Consistently use data-attributes as test hooks instead of id's

### ISSUE THREAD

**Issue by Knochenmark** [freeCodeCamp/testable-projects-fcc#276]
#### Proposal
I think it would be better to consistently use data-attributes for the testcase hooks instead of IDs.
Well, mostly the testcases are a mix of data-attributes and IDs, i.e. inconsistent.

Some advantages:
First of all data-attributes shouldnt break someones styles, when they would decided to use a different ID selector for their elements. They are easier to add or modify afterwards to progress through the testscases without breaking any styling and usually indicate already that Javascript is involved.

I've noticed that the same ID is assigned to legends in the ScatterPlot for example. A better hook would be a data-attribute and the testcase could check for 2 seperate legends. Especially since _IDs should be unique_ in a page.

https://codepen.io/freeCodeCamp/full/bgpXyK

Consider this a discussion basis and not necessarily a implementation request.

**Comment by tchaffee** [comment]
This sounds like a good idea to me. @Knochenmark would you want to take this on yourself?

**Comment by Knochenmark** [comment]
I might give it a shot tomorrow :)

**Comment by Knochenmark** [comment]
Hey, I have issues running the npm install the daplie package is deperecated and the page is not responding. Is this known? Any solutions?

`
$ npm install
npm WARN deprecated localhost.daplie.me-certificates@1.3.5: this package has been deprecated
npm ERR! Error while executing:
npm ERR! C:\Program Files\Git\mingw64\bin\git.EXE ls-remote -h -t https://git.daplie.com/OAuth3/oauth3-cli.git
npm ERR!
npm ERR! fatal: unable to access 'https://git.daplie.com/OAuth3/oauth3-cli.git/': Failed to connect to git.daplie.com port 443: Timed out
npm ERR!
npm ERR! exited with error code: 128
`

**Comment by tchaffee** [comment]
Yes, we are having problems with that package. I reported it to them, and I opened issue #277 to see if you can find a more reliable replacement.

**Comment by tchaffee** [comment]
I am trying to think of a way that you could perform local testing without that package, but I'm not sure you can. I'll keep you up to date with Daplie's response. Hopefully they can get this fixed by tomorrow when they come back to work. If not, I'll accelerate my search for a replacement.

**Comment by tchaffee** [comment]
Thinking about this suggestion a little more, one thing we have to keep in mind is that it actually might be a requirement that a div have a specific id. In which case, I don't think it's so bad that we have a test that reads `I can see a title element that has a corresponding id="title"`. @Knochenmark What are your thoughts on this? Can you give some examples of how the test narrative would change if we use data-attributes? I think it would be for the team to look at a few examples for discussion before you get too deep into the work. Thanks!

**Comment by tbushman** [comment]
@Knochenmark , do you mean data-attributes for the test suite window or for student projects? The former would be simpler if the intent is to enclose the test suite ui...

**Comment by Knochenmark** [comment]
@tbushman I dont think the button issue is related as far I can tell. You could add data-attributes as hooks there too to style the suite window if you wanted. The main reason though is that the selector for the button is not specific enough I guess. I know that bootstrap is using a lot of `!important` statements for their styles.

What I meant is that it would probably a better idea to use data-attributes instead of enforcing certain ids on attributes. Especially noticable was this since ids were used twice to fit to the tests.

@tchaffee I was thinking about something along the line of `data-test-id="title"` or simply `data-id="title"` feel free to add suggestions.

PS: I stumbled upon this on a quick search https://medium.com/@colecodes/test-your-dom-with-data-attributes-44fccc43ed4b

In another source I found at home, which I was originally searching instead of the Medium article, they used something like `data-qa-testCaseName` followed by the specific testcase to cover.

**Comment by tchaffee** [comment]
Good article, thanks.

> I was thinking about something along the line of `data-test-id="title"`. 

That would be what I've seen as suggested best practice when writing *normal* tests. My hesitation with this for these projects is we aren't teaching Campers how to write good tests. We are teaching Campers best practice about HTML and CSS and to use the id and class attributes. So my guess is that our requirements (in the form of these tests) should talk about ids and classes. @QuincyLarson @tbushman any thoughts on this?

Going into a little more detail, the idea behind using something like `data-test-...` is separation of concerns. 

1. Tests use the data attribute 
1. We can leave the id and classes for the person who writes the HTML and CSS (and JavaScript)
1. Some folks even like to leave id and classes totally to the designers (HTML / CSS) and use another set of data attributes (`data-js-....`) for the javascript to give even better separation of concerns. (I think there are some cons to that approach. E.g. selecting by class in javascript is for sure faster. There might be other cons - I haven't tried using data attributes for JavaScript yet).

In the case of these tests my take is that the Camper isn't the testing team. They are the person writing HTML and CSS. So based on the above they should have exclusive use of the ids and classes. And since they are supposed to be using classes and ids, when need to direct them to do that in our tests.

BTW, I'm not saying there are no cases in which using a `data-test-id` attribute could be considered, but I think they are going to be rare.

FYI, in the case of the ids that were used twice, that's a bug in the CodePen and we should fix it. I'll open an issue when I get a chance.

Finally, my ideas above are just a suggestion. I'm open to discussing this if anyone has other ideas or if there are questions.

**Comment by QuincyLarson** [comment]
@Knochenmark I agree that this is a great practice for writing better tests, and codebases that you plan to refactor.

This said, these projects are probably as close as a developer can get to code they don't plan to maintain. So the arguments in favor of refactorability lose a lot of their gravity here.

So I agree with @tchaffee here. In a perfect world, I'd say it'd be good to teach them this practice, but this is far from a widely-accepted practice, and it would be yet another thing we'd need to teach them before they'd be able to build projects.

So at this point, based on my understanding of the cost/benefits presented here, I don't think this change would cause more harm than good to the learner's experience.
