### ISSUE TITLE
tests break the functionality of the page

### ISSUE THREAD

**Issue by tsacinim** [freeCodeCamp/testable-projects-fcc#286]
#### Issue Description

Running the tests removes the editor content. Afterwards, the functionality is also lost.

To reproduce: 
1. select 'markdown previewer' test suite
2. click 'run tests' button
3. insert text in the 'editor' field (the preview is not updated)

#### Browser Information

* Browser Name, Version: Chromium, 64.0.3282.167 
* Operating System: Ubuntu
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

[link to codepen](https://codepen.io/tsacinim/pen/paKPbR)

this is also happening in the official example:

[link to official codepen](https://codepen.io/freeCodeCamp/full/GrZVVO)

**Comment by tbushman** [comment]
Thanks @tsacinim. Can you also share which version of react you are using?  
@tchaffee In a previous PR (#223), I added a line to configure the textarea element so that the latest versions of react can accept editor.dispatchEvent. This bug comes from that. I'll be looking into this. Sorrry.   
For reference, here is the problem discussed on react: https://github.com/facebook/react/issues/10135  
And this is what I used: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty

**Comment by tsacinim** [comment]
The version of React used is 15.6.1 (this is the version added at the moment by default in codepen, also for this version dispatchEvent is reported as not working in the react issue linked). The official codepen uses React 15.3.1 (for which the dispachEvent is reported as working).

**Comment by tbushman** [comment]
Exactly. #223 polyfills dispatchEvent for react 15.6.1, but apparently creates this new issue. Thanks for reporting.
