### ISSUE TITLE
clicking test case "arrow button" takes user nowhere 

### ISSUE THREAD

**Issue by no-stack-dub-sack** [freeCodeCamp/testable-projects-fcc#30]
#### Issue Description

These buttons take the user to a blank page within codepen. To go back you'd have to right click within the preview window, rather than use the browsers nav buttons, because then you'd be going back not in the preview but for the whole page:

![image](https://cloud.githubusercontent.com/assets/18563015/22408651/630de7c0-e64a-11e6-8147-7d79b6b67f5e.png)

**Comment by tchaffee** [comment]
@no-stack-dub-sack What is the expected behavior for those buttons?

**Comment by tchaffee** [comment]
@no-stack-dub-sack Has this gone off your radar? I'm happy to try to fix this if I can understand what the expected behavior is.

**Comment by no-stack-dub-sack** [comment]
@tchaffee thanks for the reminder. This one went unnoticed. 

To be honest, I'm not sure what the expected behavior is. I think it is to select and replay one individual test. Sometimes it half works in codepen, and the test suite will select and only run one test, but most of the time it just goes to a blank page. 

I tried noodling around at some point a while ago, but couldn't produce any different behavior. Ideally we could just remove or disable them I think, since most of our tests run pretty quickly. Although if they are meant to just select and run one particular test, it could be useful in the D3 tests or Pomodoro, any of those tests that don't happen pretty much instantaneously.

**Comment by tchaffee** [comment]
@no-stack-dub-sack  Ok, thanks for the feedback. I'll look into it.

**Comment by tbushman** [comment]
@tchaffee I was looking into a way to include markdown in the mocha modal for the calculator test and will eventually submit a PR that customizes the mocha reporter and includes working anchors  hopefully.

**Comment by tchaffee** [comment]
This does work, but it's not intuitive how it works. In order to see it working, you need to press our "Run Tests" button again, after which you'll see just that one test run. Unfortunately there is then no way to re-run all of the tests without refreshing the page. 

What's happening is that the mocha arrows / buttons just execute `mocha.run()`. However our test runner does `mocha.run()` along with a bunch of other stuff like displaying the test results modal and updating the our buttons with the number.

I see a few possible solutions:

1. Try to override the mocha buttons with our code. This will probably be a bit of work to get everything in sync.
1. Just hide those arrows with CSS.
1. Long term @tbushman may have a solution as she mentioned in comments above.

For now, I think we should just change the CSS. Our tests are pretty fast even if you re-run every test each time. It's a quick fix, and I don't think anyone is using those arrows anyway, and we haven't had complaints. No one is going to miss them.

@QuincyLarson @tbushman @no-stack-dub-sack What do you think?

**Comment by tbushman** [comment]
@tchaffee I can re-visit the Mocha custom reporter next. My branch, https://github.com/tbushman/testable-projects-fcc/tree/fix/mocha_reporter, shows a work-in-progress, mainly inside src/index.js.

**Comment by tchaffee** [comment]
@tbushman I'll leave this to you then. I wouldn't much more than a few hours getting those arrow buttons to work though. I just don't think they are very useful. If someone wants to make the case that they are an important feature, I'm open to hearing about that.

**Comment by QuincyLarson** [comment]
@no-stack-dub-sack @tchaffee  Awesome - thanks for surfacing this issue.

@tbushman thanks for helping tackle this. We will defer to you. 

We are going to start sending a lot of traffic to beta - hopefully in the next 24 hours. Thanks to help from a ton of contributors like you all, we are on schedule for shipping beta by Christmas!

**Comment by no-stack-dub-sack** [comment]
@tchaffee @tbushman nice! Glad this one was finally resolved. Everything is looking in awesome shape thanks to you guys!
