### ISSUE TITLE
Turns working code into none working code

### ISSUE THREAD

**Issue by JohnnyBizzel** [freeCodeCamp/testable-projects-fcc#300]
Tried Pomodoro and Calculator. Neither worked once I copied the code into the forked project.
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 
 
 
```

**Comment by JohnnyBizzel** [comment]
The code that works fine on codepen is copied to the forked test suite pen. I don't know how else to apply the test suite. So copy paste of CSS, JS and HTML plus addition of required libraries. Neither project I tested looks anything like my original pens and neither work.

**Comment by tbushman** [comment]
@JohnnyBizzel Your calculator works. The issue here is that the testable-projects tests look for DOM elements via css selectors (ids and classNames) and program events (clicks) and / or read DOM element contents. In order to pass the tests, you'll assign the required ids to each key on the calculator. For example, the `=` (equals) key would take the id="equals". Each test mentions which id the test is looking for. Thanks for taking part in testable-projects. We've had some issues with the css from the tests interfering with student project css, so the calculator's button styles are getting overridden. 
@tchaffee, the `div.key` css declaration is overriding this calculator's `.key` elements. I can make a PR for that if you want me to.

**Comment by tchaffee** [comment]
@tbushman That would be great if you can make a PR for the CSS issue.
