### ISSUE TITLE
Project testing in CodePen sometimes doesn't work/isn't visible

### ISSUE THREAD

**Issue by stufinn** [freeCodeCamp/testable-projects-fcc#313]
#### Issue Description
Project testing capability in CodePen sometimes doesn't work.  The green hamburger menu that should show up in the top left corner of the window is not visible.  This morning (may 15, 2018) it was working but this afternoon it is not, for each of my beta curriculm projects.

#### Browser Information

* Browser Name, Version: Chrome Version 66.0.3359.139 (Official Build) (64-bit). Also tried in FireFox Developer Edition v.61.0b4 (64-bit)
* Operating System: macOS high sierra v.10.13.2
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

Examples of where test suite should be available, but currently isn't:
https://codepen.io/stufinn/pen/ELLbrB
https://codepen.io/stufinn/pen/VxboEP
https://codepen.io/stufinn/pen/ZoKKoB

#### Screenshot
![screenshot](https://user-images.githubusercontent.com/30563561/40086035-48371c10-5862-11e8-8053-1ad9684eb531.jpeg)

**Comment by tbushman** [comment]
Thanks @stufinn . This is the same issue as #297 . Since we don't have control over that directly, until it's sorted out, this was the direction from @tchaffee : If you want to temporarily change the JavaScript settings for the CodePen, this link should at least get it working for now. When we get this fixed you will need to change it back or it will cause problems in the future.

Change this link:

https://gitcdn.link/repo/freeCodeCamp/testable-projects-fcc/master/build/bundle.js

To this:

https://cdn.rawgit.com/freeCodeCamp/testable-projects-fcc/a8c73bc53149aec717b08b9c14f2273eecd31c39/build/bundle.js

**Comment by tchaffee** [comment]
@QuincyLarson This has happened to us a few times now in the past couple of months. Gitcdn is not reliable anymore. Could you ask around about a replacement CDN that works with git and is free? I suppose we could try rawgit.cdn for a while? But maybe with your reach on social media you could ask a question and we could find out what everyone else is happy with these days? Thanks!

**Comment by stufinn** [comment]
Thanks for passing along the workaround @tbushman! And @tchaffee for looking into it.  Cheers

**Comment by tbushman** [comment]
Closing now that we're using a different CDN.
