### ISSUE TITLE
Pomodoro test timeout error

### ISSUE THREAD

**Issue by crazycat9x** [freeCodeCamp/testable-projects-fcc#335]
#### Issue Description

Timeout error, and various incorrect test results

#### Browser Information

* Browser Name, Version: Firefox
* Operating System: MacOS
* Mobile, Desktop, or Tablet: Laptop

#### Your Code / Link to Your Pen

```
 https://codepen.io/NKTien/pen/aGryad?editors=0110
 
 Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.[33]</</r.prototype.resetTimeout/this.timer<@https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:7197
```

**Comment by tbushman** [comment]
@crazycat9x Thanks. We are working on better ways of testing stateful virtual DOMs, but for now, the test queries the DOM itself and not the components and their states. If I look at `#break-length` in the inspector for example, the default innerHTML does not match the default state. Is there a way to force the component to render after setting state?

**Comment by crazycat9x** [comment]
The default innerHTML does match the default state, any changes to the state using this.setState() will rerender the component.
`<span id="break-length" className="button-number">{this.state.break}</span>`

**Comment by tbushman** [comment]
@crazycat9x OK, one problem I've seen early on is that the #reset element is not the intended click target. Consider, for example, changing this, `<div id="reset" class="reset"><button onClick={this.reset}>reset</button></div>` to this `<div class="reset"><button  id="reset"  onClick={this.reset}>reset</button></div>`

**Comment by tbushman** [comment]
@crazycat9x ...and another thing that helps pass these tests is to match the display strings to the test, i.e. `'00:00'` instead of `'0:00'` (two-digit minutes). With these two fixes, almost all of the non-audio tests pass. I'll look into the others.

**Comment by crazycat9x** [comment]
Thanks, have you had any luck finding what still isn't correct?

**Comment by tbushman** [comment]
@crazycat9x IT looks like you've got most of it going! I love the animation you've created. I'll keep looking.

**Comment by tforward** [comment]
@tbushman I'm having similar problems to @crazycat9x if you could take alook at mine as well? I've read over the user stories and from what I understand the app is doing what it is asked but the tests don't see it that way... :(

**Comment by tbushman** [comment]
@tforward OK will do. Could you please also share the link to the repository or even only the react code? 
@crazycat9x @tforward For this test suite in particular, I have come to assume that the tests themselves are not error prone. These errors may be due to non-synced DOM and state, which goes into a separate discussion of means of testing virtual DOM in an efficient way. Thanks for your patience.

**Comment by tforward** [comment]
@tbushman [Repo](https://github.com/tforward/fccPomodoro) , it's Vanilla JS

**Comment by tbushman** [comment]
@tforward Thanks. Will you shift the `id` attribute from the icon to the button and see if that helps?
From  
```
    <button class="center no-btn-style">
        <i id="reset" class="fas fa-redo-alt"></i>
    </button>
```  
to  
```
    <button id="reset" class="center no-btn-style">
        <i class="fas fa-redo-alt"></i>
    </button>
```

**Comment by tforward** [comment]
@tbushman I've done what you suggested above but same result any other ideas?

**Comment by tbushman** [comment]
@tforward Not yet. Thanks for your patience.

**Comment by tbushman** [comment]
@tforward I'm going to open a separate issue for this. Our tests presume use of setInterval / setTimeout. It looks like we'll need to access the Tock Object's embedded setTimeout and setInterval functions to speed up the countdown and I don't know yet how we'll do that.

**Comment by tbushman** [comment]
@crazycat9x Back to your project, I was able to get all the non-audio tests to pass by changing the setState at line 85 to  
```
    this.setState((prevState, props) => ({
        start: true,
        currentMinute: countTime,
        targetMinute: countTime,
        currentSecond: 0,
        status: status
     }));
```  
...since you already have a separate function for `decreaseTime` that decrements minutes and seconds, the test checks your code at the moment of the switch, and your timer was reading at, for example, `00:59` instead of the required `01:00`.

**Comment by crazycat9x** [comment]
But the timer wouldn't be accurate anymore thou. Because there would be 1 sec between 00:00 session and 5:00 break, shouldn't it be instant and reading at the switch be 04:59?

**Comment by tbushman** [comment]
@crazycat9x Good question. :) The switch and the test of the switch is instantaneous at the moment the timer reaches 00:00. The test expects the timer to start with the number of minutes set in either break or session inputs at that moment, so that with the next iteration, the timer will read :59. I feel less-than-qualified to give a definitive answer on this one, though.  
I will leave this open and let others chime in when they have time.

**Comment by tchaffee** [comment]
@crazycat9x It looks like the only failing tests now are the audio tests? From what I can see from your CodePen, that's not implemented yet. Can we close this, or do you need something else? Thanks.

**Comment by crazycat9x** [comment]
Yes, you can close this now, thank you :)
