### ISSUE TITLE
Pomodoro Test Suite Bug

### ISSUE THREAD

**Issue by Enikol** [freeCodeCamp/testable-projects-fcc#41]
#### Issue Description
I somehow broke the Pomodoro test suite. I ran it on a nearly finished project, it gave me 21/25 passed tests, I change one symbol in my code ( wrote "<" instead of "<=") and ran it again, and it gave me '"before each" hook' and '"after all" hook' errors (screenshot below). I changed the code back just to be sure, but it still gave me this errors. I reloaded the page, closed it and opened again - nothing helped. Other test suites on other projects work fine.

#### Browser Information

* Browser Name, Version: Chrome, 56.0.2924.87
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code
 Here's my pen: http://codepen.io/enk/pen/YNjGGr
 

#### Screenshot

![pomodoro](https://cloud.githubusercontent.com/assets/19998290/22700010/351f4fda-ed6a-11e6-8b2e-6b40b5c13e0f.jpg)

**Comment by no-stack-dub-sack** [comment]
@Enikol Hmmm... this is interesting, especially considering it was working previously. Can you point out to me where you made that change in you code so I have a better chance of diagnosing this correctly? This test suite in particular has been a bit difficult from the get go to get right... thanks!

**Comment by no-stack-dub-sack** [comment]
@Enikol Ok, so quick update, I'm thinking it is not where you changed that symbol that was the cause (which would have struck me as very odd). This perhaps was happening for a while but went unnoticed because you had been playing with the timer as you made it? Because when you run the timer first, then run the test suite, it runs - not sure why yet. 

It's passing 23/26, there is something off with the code I think that will let it pass all 26, but not sure what that is yet, and the error messages are unfortunately not helpful (they should be) - it does seem to be functioning as expected though, but when you watch the tests run, the break starts counting down from 25, which should never be the case, if you watch the tests run on the example project you will see this. 

So doing a bit more digging, but just wanted to let you know it wasn't completely broken. It likely has something to do with the reset button which was a little buggy for me after certain button combinations, and this is what's running in the the before and after hooks...

**Comment by no-stack-dub-sack** [comment]
@Enikol edited comment above (tagging you again in case you saw it before I edited it)

**Comment by Enikol** [comment]
@no-stack-dub-sack Thank you so much! I really need to learn check the console more often)
(Also, thank you for accurateInterval dependency, I saw it on example project and couldn't resist, because I've already tried to make a timer in plain JS with setInterval and it was really painful)

**Comment by no-stack-dub-sack** [comment]
@Enikol No prob! Also going to push some changes soon that will throw better errors. I'll let you know when so you can see. Locally, if I run your project against the tests as it was before you fixed it, much more helpful errors are thrown!

**Comment by no-stack-dub-sack** [comment]
@Enikol Ok! Depending on when you read this, try out switching your pen back and see the new, more helpful errors! If you see this soon, you will need to replace the gitCDN link in your pens JS settings with this link instead since the changes take a while to propagate down to the production CDN: https://rawgit.com/freeCodeCamp/testable-projects-fcc/master/build/bundle.js 

Let me know if you think these new errors would have helped! Thanks again for helping out 😄

**Comment by Enikol** [comment]
@no-stack-dub-sack Checked it out, new errors are really helpful! Thank you!
