### ISSUE TITLE
8/10 test result for the tribute project

### ISSUE THREAD

**Issue by cathyshs** [freeCodeCamp/testable-projects-fcc#440]
#### Issue Description

When I run the test for this tribute project. It reports back 8/10. I don't know how and where to find the bugs. Thank you.

#### Browser Information

* Browser Name, Version: chrome
* Operating System: mac ios High Sierra Version: 10.13.5
* Mobile, Desktop, or Tablet: MacBook Air

#### Your Code / Link to Your Pen

```
 
**https://codepen.io/Cathyshs/pen/ZjENMW** 
 
```

#### Screenshot

![screen shot 2018-07-10 at 7 39 27 pm](https://user-images.githubusercontent.com/23640434/42547856-ffe8d32a-8478-11e8-856d-fe44b0f46427.png)

**Comment by tbushman** [comment]
@cathyshs One of the errors was due to an extra space: `target=" _blank"` so change that to `target="_blank"`  
The other error was related to your `#image` element. The test says to use `max-width` (instead of width -- even though width gives the same result). Sorry. The other thing the test points out is to use `display: block;`  This refers to the `#image` element as well.

**Comment by cathyshs** [comment]
Thank you so much for your help!! I corrected the target="_blank" one and run the test again. It shows one more error left instead of two!!! However after I changed the #image from width into max-width, it still shows one error left.:( Also the change changed my formate of the image somehow.

**Comment by tbushman** [comment]
I think you got it! It was `display: block` I think. All tests are passing now. Take care.

**Comment by tbushman** [comment]
@cathyshs Such a great feeling! Congrats! Thanks for letting us know.
