### ISSUE TITLE
Tests don't show on Chrome; show on Firefox but don't show results

### ISSUE THREAD

**Issue by dtujmer** [freeCodeCamp/testable-projects-fcc#452]
#### Issue Description

The menu button for testing doesn't show on Chrome, but shows on Firefox. On Firefox, tests work, but when I click to view details about passes/fails, there is no text in the pop-up window.

#### Browser Information

* Browser Name, Version: Firefox Quantum 61.0.1. // Google Chrome 67.0.3396.99
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```
 https://codepen.io/dtujmer/pen/QxPBdz
 
 
```

#### Screenshot

![image](https://user-images.githubusercontent.com/29843076/42728276-5e45d044-87b7-11e8-9f86-50d02960e941.png)

**Comment by tbushman** [comment]
@dtujmer Sorry about this! Our test suite uses the `#mocha` `id` for the result window. If you change your `#mocha` id that will pass, but I'm keeping this open ...

**Comment by tbushman** [comment]
If we can containerize, iframe-ize, or shadow-dom-ize our test suite in any way, we can avoid these problems.  
I will re-try the shadow dom because it was working in Chrome and maybe it's working in FF in the meantime...  
The problem with the iframe was that the elements of the test suite are on the far left and right of the screen, creating a pointer-events surface without click-through to projects. Turning off pointer-events for the iframe renders the test window within it inoperable.

**Comment by tbushman** [comment]
Another problem with the iframe approach was that the `#mocha` reporter modal wouldn't attach / append inside the `iframe` in case someone wants to retry that.
