### ISSUE TITLE
React Markdown Previewer Tests

### ISSUE THREAD

**Issue by Bgraham2** [freeCodeCamp/testable-projects-fcc#472]
#### Issue Description

Test number 6 fails with this assertion error:
AssertionError: #preview does not contain the H1 element represented by the markdown in the #editor field with the inner text Markdown  : expected 0 to be at least 1

however you can see the h1 tag in the developer tools so it is working.

#### Browser Information

* Browser Name, Version: Chrome Version 64.0.3282.167 (Official Build) (64-bit)
* Operating System: Windows 7
* Desktop

#### Your Code / Link to Your Pen

```
 https://codepen.io/bgraham2/pen/pymJKo
 
 
```

#### Screenshot

![image](https://user-images.githubusercontent.com/12739167/43012322-a0757e58-8c0b-11e8-839f-feeee68dc7cb.png)

![image](https://user-images.githubusercontent.com/12739167/43012465-e2bf81b4-8c0b-11e8-8a94-1f547e0b70fb.png)

**Comment by tbushman** [comment]
@tchaffee Could you please look at this? I tried updating it to react/15.x and adding ReactDOM and ReactDOM.render and test 6 still fails. All appears to be in order in this project.

**Comment by tchaffee** [comment]
@Bgraham2 I found the problem with test #6. It's because there is a space at the end of your `# Markdown `. I'm not sure if it's a bug in the markdown software or something you have to fix, but we test if your markdown produces the same exact text as in the preview. Your preview has the trailing space stripped from it so it's just `<h1>Markdown</h1>`. If you remove the space from the end of that word, you will pass the test. Any other questions just let me know, but please close this if you are happy with the answer.

**Comment by tbushman** [comment]
@tchaffee Thanks!! Wow. O.O ...  
Maybe we should be using `.trim()` in these tests. This was a real needle in the haystack.

**Comment by tchaffee** [comment]
@tbushman I think it's better leaving it as is. An extra space that causes a bug is a good learning experience. That's how I found it so quickly, been there done that ;-)
