### ISSUE TITLE
Technical Documentation Bug with Layout #1 test

### ISSUE THREAD

**Issue by emptyport** [freeCodeCamp/testable-projects-fcc#487]
#### Issue Description

When running the test for the technical documentation project, the test for my navbar always being onscreen fails even though the navbar is always on screen.

Steps to reproduce:
1-Go to the Codepen Pen
2-Run tests
Expected result: All tests pass
Actual result: Layout test 1 fails even though the navbar is always on the screen.

The widget that opens up the test itself is moving, but the navbar doesn't move. The test does pass when the screen is sized large enough even though you still have to scroll to see all the documentation.

#### Browser Information

* Browser Name, Version: Google Chrome Version 65.0.3325.181 (Official Build) (64-bit)
* Operating System: elementary OS 0.4.1 Loki Built on "Ubuntu 16.04.5 LTS" Linux 4.13.0-38-generic
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

https://codepen.io/emptyport/pen/ejGONM

**Comment by emptyport** [comment]
This happens both in Codepen and when I serve the web page locally on localhost

**Comment by tbushman** [comment]
@emptyport I tested your project in Chrome and Firefox and don't see errors. If it's still a problem, let us know.

**Comment by emptyport** [comment]
I ran the tests again and everything seems to be fine now.

**Comment by TaraBryn** [comment]
@emptyport I ran into the same issue and it seems to have "fixed iteslf" it turns out that if you move the #navbar to the top with a media query, and the viewport is less than the width required for the navbar to be on the left, then it fails, if you expand the viewport, then it passes with the same code. Perhaps there is a way for the test to account for that?

screenshot before (passes test):
![image](https://user-images.githubusercontent.com/28311501/59567085-e8360980-9036-11e9-8305-cbc7163c7fcb.png)

screenshot after:
![image](https://user-images.githubusercontent.com/28311501/59567093-fedc6080-9036-11e9-9956-c0ee15ecce17.png)

link to my pen: https://codepen.io/TaraBryn/pen/GboLRg
