### ISSUE TITLE
fCC JS Tribute Page Test

### ISSUE THREAD

**Issue by jredick18** [freeCodeCamp/testable-projects-fcc#49]
#### Issue Description

When I run the JS Tribute Page Test, I get a failure for #2 of the Layout (The <img> element should be centered within its parent element.).

#### Browser Information

* Browser Name, Version: Google Chrome, Version 56.0.2924.87 (64-bit)
* Operating System: Chrome OS
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

...

<style>
#img-div {
  margin: -5px;
  margin-top: 20px;
  width: 100%;
  border: 5px solid white;
  background: white;
}
 #image { 
  display: block; 
  margin: auto;
  max-width: 100%;
 }
 </style>

<html>
<div id="img-div">
      <img id="image"
           src="http://cosmicconvergence.org/wp-content/uploads/2016/01/TeslaPortrait1.jpg" alt="Nikola Tesla with Tesla Coil">
</div>
</html>
```

#### Screenshot
<!-- Add a screenshot of your issue -->

![screenshot 2017-02-18 at 12 51 13](https://cloud.githubusercontent.com/assets/14083753/23095516/01779ca6-f5d9-11e6-9bd9-d40bf8cd35cb.png)

**Comment by no-stack-dub-sack** [comment]
@jredick18 can you please post the link to your pen so I can check it out? 

This test has been giving me a lot of problems, and thought we just had the last of them fixed... guess not!!

**Comment by jredick18** [comment]
@no-stack-dub-sack sure thing, I'm going to tweak a few things before submitting but I just wanted to make sure I was passing the tests.

> [http://codepen.io/jredick18/pen/ZLVERy?editors=1100](url)

Thank you!

**Comment by no-stack-dub-sack** [comment]
@jredick18 try re-sizing your browser window to different sizes, running the tests in full page mode, and running the test in full page mode at different browser widths - the test is usually passing for me, but at certain widths, it's ever so slightly off by one PX (looks like a need to afford an 11 px delta, not 10).

Every time I get the test to fail, it's always by one PX, which is strange, because the error message that you showed shows off the 11000?? Give it another try and tell me if you get an error that is more similar to this one: 
![image](https://cloud.githubusercontent.com/assets/18563015/23141740/431ccd30-f786-11e6-94c7-bd03548f13c8.png)

**Comment by no-stack-dub-sack** [comment]
@jredick18 ok, I just made a quick PR, I can no longer get the test to fail on my end (also in chrome), so if it still fails for you, it is a different problem. Let me know how you make out on your end!

Thanks again for reporting this and project looks great by the way!

**Comment by jredick18** [comment]
@no-stack-dub-sack alright so I opened it up and tested, everything checks out! Yes I noticed the number the px were off by and every time they were slightly different. Thanks again!

**Comment by no-stack-dub-sack** [comment]
@jredick18 No prob! Glad it's working - this test has been extremely finicky, so hoping this is the last I will have to see of it! Closing the issue since it looks like this PR did the trick.
