### ISSUE TITLE
[Drum Machine] Test 3

### ISSUE THREAD

**Issue by christophherr** [freeCodeCamp/testable-projects-fcc#50]
#### Issue Description

The test fails if the letters are inside p tags. 
span tags work. 
A bit unexpected (even though the text mentions "inner text").

Also wanted to mention that Test 3 pretty much expects a qwerty keyboard layout. 
Doesn't make much sense on my qwertz keyboard to use z,x,c for the bottom row.

#### Browser Information

* Browser Name, Version: Chrome 56.0.2924.87 (64-bit)
* Operating System:  Windows 10
* Mobile, Desktop, or Tablet: Laytop

#### Your Code

```
 This fails:
<div class="drum-pad" id="heater-4">
     <p class="drum-key">A</p>
 
 This passes: 
<div class="drum-pad" id="heater-4">
     <span class="drum-key">A</span>
```

**Comment by no-stack-dub-sack** [comment]
@christophherr that really is unexpected, I had been under the impression that `innerText` would target the text content of the inner most node. Very strange. Looking into alternatives

**Comment by no-stack-dub-sack** [comment]
And yeah, to your other point, I have to admit I never once even came close to thinking about that in designing these tests

Not sure what the best thing to do about it is though. I have to think on that one

**Comment by no-stack-dub-sack** [comment]
Ok, so both tests 3 and 4 were failing for me when I made this change to my project, and I figured out why. In mine at least, the problem has to do with react and how babel compiles a <p> element vs. a <span> - I THINK (but not totally sure). Ultimately, I believe a span is kept inline, while a <p> ends up on a new line, and innerText was picking up these newline characters, i.e. `\n`. So in the end, I just added a regex, which eliminates any white space, so that all we will get is the text content itself. This fixed it on my project, but again, this is React and not sure what you're using. I'm pushing the changes in a few, and feel free to use the DEV cdn to see if the changes fixed it on your end.

Thanks!

**Comment by no-stack-dub-sack** [comment]
@christophherr Ok, the changes should be live in a few minutes on the DEV cdn and a few hours on the PROD cdn - can you check and let me know if this fixes the issue on your end and if not re-open?

**Comment by christophherr** [comment]
@no-stack-dub-sack 
Thank you! 
The test is passing with `p` tags now. (using vanilla JS)

Regarding the keyboard layout, QWERTY is by far the most common.
I´m not sure if a change would be necessary or even more confusing.
(Looks like `ert - dfg - cvb` should be the same for QWERTY, QWERTZ, AZERTY and QZERTY.)
