### ISSUE TITLE
Tests and Vue.js

### ISSUE THREAD

**Issue by christophherr** [freeCodeCamp/testable-projects-fcc#59]
#### Issue Description
As mentioned on the Forum and in issue #31, tests are failing when using Vue.js.
The issue is that Vue updates the DOM asynchronously.
[https://vuejs.org/v2/guide/reactivity.html#Async-Update-Queue](https://vuejs.org/v2/guide/reactivity.html#Async-Update-Queue)

Here is an example test from the official docs: 
https://vuejs.org/v2/guide/unit-testing.html#Asserting-Asynchronous-Updates
Assertions on DOM updates resulting from state change will have to be made in a Vue.nextTick callback:
```// Inspect the generated HTML after a state update
it('updates the rendered message when vm.message updates', done => {
  const vm = new Vue(MyComponent).$mount()
  vm.message = 'foo'
  // wait a "tick" after state change before asserting DOM updates
  Vue.nextTick(() => {
    expect(vm.$el.textContent).toBe('foo')
    done()
  })
})
```
I haven't looked at it in depth but there doesn't seem to be an easy way to just add some "Vue compatibility" to the existing tests.
The Vue page on unit tests mentions that it is planned to work on a collection of common test helpers that might make this easier.

It might be best, for now, to add a notice to the User stories and/or test suite that tests will fail with Vue.js.

**Comment by no-stack-dub-sack** [comment]
@christophherr Yeah, I agree. I think the best thing for now will be to put an alert that will warn users of this. I wonder if there's a way to detect Vue.JS? That way we could warn only when it's appropriate

**Comment by tbushman** [comment]
@no-stack-dub-sack If the app is named, like `var app = new Vue(...)`, the test can determine if it's a Vue instance with `app._isVue`. I have been running into a lot of problems trying query nextTick. I can submit a PR with an alert that tests for Vue, or as @tchaffee has suggested, the tests can each require a specific framework.

**Comment by tchaffee** [comment]
@tbushman Since you already gave this some attention, and it still looks difficult, let's go ahead with specifying what framework (if any) is required for each project. The earlier projects should not use any framework and should just be plain HTML. The projects from the React section of the program should require React. I don't see this as a problem at all. We don't support other frameworks in the D3 section. It's a hard requirement that those projects be built using D3. And this does not not stop us from adding Vue support in the future if we find a reasonable way to do that.

**Comment by tchaffee** [comment]
Closing this. We've added a "tech stack" section to each test suite, and support for Vue is not on our immediate radar. It's a long term goal, and we con't need an open issue to track it.
