### ISSUE TITLE
[D3: Tree Map]: Does not display in Safari

### ISSUE THREAD

**Issue by no-stack-dub-sack** [freeCodeCamp/testable-projects-fcc#61]
@Christian-Paul, @paycoguy Hey guys, so... we finally got the test suite running in browsers other than Chrome - but now, we're discovering that individual projects not seem to have little eccentricities of their own. 

Tree map is one - (most) tests fail and visualization does not show up at all in Safari. Haven't yet tested in FireFox and don't have a PC for IE or Edge. Can either of you investigate this on other browsers and let me know? And possibly look into why this is?

Thanks! Going to be opening up some other issues for other projects as well, feel free to jump in if you have any ideas. I'll tag you guys on D3 issues. 

**EDIT:** Oh yeah, also, clicking the "Tests" button, does not bring up the modal for some reason, so you can't see what the issues are

**Comment by Christian-Paul** [comment]
@no-stack-dub-sack I just tested it on edge and IE. the visualization doesn't show up on either. The modals show up on both, but the styles are messed up on IE.

The reason the chart doesn't appear is because of how the data selection works. We set the chart to check the url to decide which dataset to display, but it looks like IE/Edge doesn't support this method.

`new URLSearchParams(window.location.search);`

This is the code responsible for the error: 'URLSearchParams' is undefined

According to Mozilla, this isn't supported on IE or Safari (and I'm getting the same error on edge)
https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams

**Comment by paycoguy** [comment]
@no-stack-dub-sack I have updated my codepen to make the TreeMap appear on Safari, IE, Edge, Firefox, and Chrome.

http://codepen.io/paycoguy/pen/JWXXmq

**Comment by paycoguy** [comment]
@no-stack-dub-sack I submitted  PR https://github.com/freeCodeCamp/testable-projects-fcc/pull/72 a week ago.  Do you have any questions about it?

**Comment by Lakston** [comment]
Everything works for me on FF, Chrome, Canary and Safari, testable project here : https://lakston.github.io/d3-heatmap/

So I guess we can close this ?

**Comment by tchaffee** [comment]
Closing because this is outdated. We will address cross-browser support in an upcoming phase.
