### ISSUE TITLE
mistake

### ISSUE THREAD

**Issue by rubendmatos1985** [freeCodeCamp/testable-projects-fcc#624]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 https://codepen.io/Ruben1985/pen/rZNzBV
 
 
```

**Comment by rubendmatos1985** [comment]
the header is always at the top but the script do not recognize it. Any idea??

**Comment by tbushman** [comment]
@rubendmatos1985 Is there a way you can structure your project so that the `header` always has `position: fixed;` ? For example, if you remove the script for switching the `float-header` class, you can add `class="float-header"` to `<header>` statically, then add `margin-top: 150px;` to `#section1` ...
