### ISSUE TITLE
profile link

### ISSUE THREAD

**Issue by rudylemus** [freeCodeCamp/testable-projects-fcc#636]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 
 
 
```

**Comment by tbushman** [comment]
Hello, please provide some more information about the error you are experiencing. Indicate which test is failing and provide a screenshot, a code sample, or a link to your project.

**Comment by floydkim** [comment]
Hello.
I think it's about "Build a Personal Portfolio Webpage" challenge.

I couldn't pass the test #8 "My portfolio should have a link with an id of "profile-link", which opens my GitHub or FCC profile in a new tab." although there was no wrong code :
`<a id="profile-link" href="">link</a>`

I solved this by replacing "(double quotation) to ' (single).
`<a id='profile-link' href="">link</a>`

Please correct this bug.

(I'm using Chrome 70.0.3538.102 (64bit) on macOS Sierra.)

**Comment by ValeraS** [comment]
@floydkim The test does not depend on quotation marks. Provided code does not contain `target="_blank"`, which causes an error. If you still consider the error in quotes, please give a link to your pen with the error reproduction.

**Comment by floydkim** [comment]
@ValeraS `target="_blank"` is omitted because I thought this attribute is not important about this problem. :)

And I found quotation mark is not a solution.
I'm still working on this portfolio challenge (contents and details) so some tags are added after I wrote a comment.
Now, after changing single quotation mark to double, tests are passed.
I'm confused.

[https://codepen.io/for12/pen/yQbzgd](url)
now it has no error so I don't recommend you to visit this pen.
