### ISSUE TITLE
ISSUE on the decimal point notation

### ISSUE THREAD

**Issue by paulTchaa8** [freeCodeCamp/testable-projects-fcc#672]
#### Issue Description
Hi. In fact it's not really a huge issue, though i would like to ask that for some of us who are francophons as sample, we use the comma**(,)** instead of the decimal dot notation**(.)** , and obviously i know that when doing so, the checker will not accept. I could use a regex to change it. What do you think about that dears??

#### Your Code / Link to Your Pen
this is [my react calculator](https://codepen.io/paulTchaa8/pen/NOmbwM)

**Comment by tbushman** [comment]
@paulTchaa8 A valid point, yes. :) Thank you.

**Comment by thecodingaviator** [comment]
@tbushman I'm going ahead with this issue, but I'm not sure how to do 2 alternate options in :

![image](https://user-images.githubusercontent.com/34807532/55880901-4a9a0600-5bbf-11e9-815f-3f09245e5a59.png)

**Comment by tbushman** [comment]
@thecodingaviator @paulTchaa8 Upon consideration, I think we shouldn't accommodate a comma. I don't think any digital calculators use the comma. Please correct me if I'm wrong.

**Comment by thecodingaviator** [comment]
I'm not sure of any digital and most physical calculators that might be using the , . I guess we should keep it as wontfix?

**Comment by ojeytonwilliams** [comment]
I did a quick search for calculatrice and found http://www.calculette.com/ http://www.la-calculatrice.com/calculatrice-en-ligne.html http://www.la-calculatrice.fr/ which do partially use commas.  I say partially, because when you click on the comma it is displayed as a decimal point.

So, technically it is used, but even dedicated francophone calculators just use it as a proxy for `.`

**Comment by thecodingaviator** [comment]
I feel it is best to leave it as is, the comma introduces unnecessary complexity. I'm locking the discussion to collaborators from now on.
