### ISSUE TITLE
Tribute Page tests 1 & 2 do not match HTML5 elements taught in course 

### ISSUE THREAD

**Issue by aaronRhodebeck** [freeCodeCamp/testable-projects-fcc#77]
#### Issue Description

Content tests 1 and 2 test for document.getElementById(), could test for document.getElementByTagName(). This would match the syntax of using `<main>` and `<title>` tags as taught in the course work.

**Comment by aaronRhodebeck** [comment]
I looked at trying to fix this and submit a pull request myself, but I am very new at this and it seems there are a lot of moving parts in submitting breaking changes. I would be happy to make the changes and submit a pull request if someone is interested in helping my make sure that I have all the files and tests in the proper place for my pull request.

**Comment by no-stack-dub-sack** [comment]
@aaronRhodebeck using getElementsByTagName as you suggest would not be the best solution, because that would grab every element with that tag name, and we'd have to narrow it down from their. Probably the solution is a lot simpler, as I do see your point.

We could simply change the instructions to the following:

- `1. My tribute page should have a main element with corresponding id="main", which contains all other elements.`
- `2. I should see an element with corresponding id="title", which contains a string (i.e. text) that describes the subject of the tribute page (e.g. "Dr. Norman Borlaug").`

This removes `<div>` and `<h1>` from each instruction respectively, and lets the camper decide which tag they want to use, while not breaking any existing solutions or changing the tests in any way. This way also, using `main` and `title` HTML5 tags would be implied but not required

Being a pretty simple change, and already 1 PR in to this repo, I think you are fairly well equipped to take this on. Want to give it a shot? You can feel free to PM me on gitter if you have any questions.

**Comment by no-stack-dub-sack** [comment]
FCC_Global.assert(document.querySelectorAll("#main div, #main a, #main h1, #main img").length, 'div with id="main" must contain other elements');

You would also need to change the reference to `div` in this line to "element"

**Comment by aaronRhodebeck** [comment]
Thanks for being so helpful! I submitted the pull request changing the instructions.  I am currently going through the full beta version of the site, so I will absolutely help out when I find issues, hopefully fixing them myself.
