### ISSUE TITLE
Tribute Page - Responsive Image with Bootstrap 4 - Img-fluid

### ISSUE THREAD

**Issue by justindstauffer** [freeCodeCamp/testable-projects-fcc#782]
#### Issue Description

Bootstrap 4 uses the class="img-fluid" for responsive images. I used this class on my image but the test is failing. The image sizes down compared to the parent element and does not exceed the actual size of the image. 

#### Browser Information

* Browser Name, Version: Chrome, Version 71.0.3578.98 (Official Build) (64-bit)
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```
 https://codepen.io/justindstauffer/pen/aXOYgL
 
 
```

**Comment by petercr** [comment]
I just ran the tests on your CodePen page and your project passed all 10 tests for the tribute page. 
Is there another issue I am missing?

Thanks,
Peter Cruckshank 

![2019-01-24](https://user-images.githubusercontent.com/26460352/51686751-f66b8680-1fbe-11e9-80d9-5912b065d8c1.png)

**Comment by justindstauffer** [comment]
I added some CSS code - display: block; AND margin: auto;

This fixed the problem but the class"img-fluid" does that. So I am confused
why I had to add those redundant lines of CSS.

**Comment by petercr** [comment]
Good questions, so I looked into it 😃 🤓 

So since the project _doesn't **require**_ Bootstrap the easiest way to test for the image being responsive and centered is to check the CSS properties of the `<image>` element to see if `display:` is set to `block`. And **if** you set `display: block` then the image gets pushed to the left side of the `div`. This is why you need the extra line for `margin: auto`.

And that's what the test is doing, which is why it fails with the default Bootstrap classes. Bootstrap is setting `img-fluid` properties to `max-width: 100%` and `height: auto`.
Which does the exact same thing, but in a different way. 

I hope that this makes sense to you as to why the test failed even though the project functioned correctly. 

Have a great day, 

Peter Cruckshank 😎 👍
