### ISSUE TITLE
Drum-machine Tests 5 & 6.

### ISSUE THREAD

**Issue by astron97** [freeCodeCamp/testable-projects-fcc#784]
#### Issue Description

Hi, am a noob trying to learn the ways of react . . . I bound the functions directly to each component. I don't know why tests 5 & 6 are not working even though it is triggering sound. Any help/workarounds would be appreciated. Thanks. 

#### Browser Information

* Browser Name, Version: Chrome, 71.0.3578.98 .
* Operating System: Win 10 Home.
* Mobile, Desktop, or Tablet: Desktop.

#### Your Code / Link to Your Pen

```
 https://codepen.io/astron97/pen/MZLabY
 
 
```

#### Screenshot

![screenshot 1](https://user-images.githubusercontent.com/45058613/51766974-0b046780-2102-11e9-86d3-42ba3ed3780f.png)
![screenshot 3](https://user-images.githubusercontent.com/45058613/51766982-0dff5800-2102-11e9-8982-120b44b94987.png)

**Comment by astron97** [comment]
https://codepen.io/astron97/pen/MZLabY

**Comment by tbushman** [comment]
@astron97 The main issue is the duplicate `id`s. Since the `<audio>` element is required to have the alphabetical letter, please use a different `id` value for the `<button>` elements.  
The `<audio>` element itself is what the app will `play()`, so using the `Audio` constructor will not pass the tests.  
```  
soundPlay(beats, text, key) {
  var sound = document.getElementById(key); // instead of `new Audio(beats);`
  sound.play();
  sound.currentTime = 0;
     this.setState({
    displayText: text
  });
}  
```  
where `key` is the `<audio id>`, or alphabetic letter.  
After sorting that out, I wasn't getting events from keypresses, so that will need to be configured.  
  
We should probably rewrite the tests to allow usage of the `Audio` constructor, but for now, use `<audio element>.play()`

**Comment by astron97** [comment]
Hi, @tbushman , many thanks for the elaboration. I made the change of id and used the audio element . The audio is playing when a button is clicked but I can't understand what you meant by not getting event on a click.

**Comment by tbushman** [comment]
@astron97 Hi, sorry I was short. In my understanding, your project does not yet include handlers for `keypress` events. I'm actually not sure.

**Comment by astron97** [comment]
@tbushman Yea , my bad , Sorry I mistook click and keypress events. I understood what the 6th test is about. Thank you for the prompt reply.
