### ISSUE TITLE
The <header> element with id="header" should always be at the top of the viewport.

### ISSUE THREAD

**Issue by alberto-marin** [freeCodeCamp/testable-projects-fcc#80]
#### Issue Description

When running the test in codepen I get the message "The <header> element with id="header" should always be at the top of the viewport." The header is already at the top.

#### Browser Information

* Browser Name, Version:  Google Chrome 56.0.2924.87 (64-bit)
* Operating System: macOS Sierra 10.12.3 (16D32)
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

 https://codepen.io/albertomarin/pen/BWmvgE
 
#### Screenshot

<img src="http://i.imgur.com/7PrAmMC.png">

**Comment by kev0587** [comment]
@alberto-marin,

You're getting this error because as you scroll down on your page, everything nested within your header element is not always shown at the top of the viewport.

Try figuring out a way to always have your navbar displayed at the top of the viewport, even when scrolling to the bottom of the page.

**Comment by alberto-marin** [comment]
Oh my! Thank you so much. I did a wrong interpretation of the message. I fixed it adding to the #header:
position: fixed;
top: 0;
background-color: #fff;
width: 100vw;
and giving some space to the top of the #main

Thank you
