### ISSUE TITLE
Test Suite overrides page margin

### ISSUE THREAD

**Issue by kevcomedia** [freeCodeCamp/testable-projects-fcc#87]
#### Issue Description

The test suite overrides the project's `<body>`'s margin and sets it to 0. [Example](https://codepen.io/graycoatkev/pen/YZmzbv?editors=1100).

#### Screenshot

![image](https://cloud.githubusercontent.com/assets/17902987/25417863/ed8dadae-2a79-11e7-869c-0e5517532b93.png)

![image](https://cloud.githubusercontent.com/assets/17902987/25417892/23f9439e-2a7a-11e7-8f2c-f3e57cacc9ae.png)

**Comment by no-stack-dub-sack** [comment]
@kevcomedia Thanks for pointing out this issue. I did some investigating, because this was news to me, and it turns out it is not the test suite itself, but Mocha's CSS which is overriding this rule in your example:
```css
#mocha h1, #mocha h2, body {
    margin: 0
}
```
This may be because we have mocha css hard coded into the project in order to keep everything bundled nicely for campers, I suspect that if mocha was pulled in as a CDN, the order of the stylesheets would change, and this would not be the case. 

That said, I did check for other such conflicts and there are none, so a quick solution to this would just be to add `!important` to your rule. 

Hope this helps! Thanks again and happy coding!

**Comment by kevcomedia** [comment]
If the css is hard-coded, maybe it can be removed? It's the only (simple) selector in the mocha css that doesn't target any class or id, and it doesn't seem to serve any real purpose. And it might trip other campers later on, especially when beta goes live.

**Comment by no-stack-dub-sack** [comment]
@kevcomedia You know, I thought of this yesterday just after leaving the comment as I looked closer at the code. I would agree &mdash; so far as I can tell, in this instance it seems to serve zero purpose, and it definitely may help more inexperienced campers especially. 

Feel like making a quick PR? Again, thanks for bringing this to my attention. 

p.s. and sorry for the late reply, I've been very caught up in another project lately, and unfortunately I'm the only one monitoring this repo at all right now.

**Comment by kevcomedia** [comment]
There you go 🙂 
If something's not right let me know. And I don't mind the late reply at all 😃
