### ISSUE TITLE
Run Test button click on the survey form

### ISSUE THREAD

**Issue by Tiiso** [freeCodeCamp/testable-projects-fcc#886]
#### Issue Description

I opened the survey form on codepen.io.
I did not fill the form 
I then clicked the run tests button and the tests button turned green with the 17/17 pass score

#### Browser Information

* Browser Name, Version: Google Chrome, Version 74.0.3729.131 (Official Build) (64-bit)
* Operating System: Windows 10
* Mobile, Desktop, or Tablet:  Desktop

#### Your Code / Link to Your Pen

``

https://codepen.io/freeCodeCamp/full/VPaoNP
 
```

#### Screenshot
<!-- Add a screenshot of your issue -->
![Screenshot (36)](https://user-images.githubusercontent.com/34275171/57176509-31504680-6e59-11e9-9816-d9ba998406a7.png)

**Comment by abhishekakade** [comment]
@Tiiso, the tests for this project DO NOT check if the form has been filled or not. It only does a few client side data validations like if `type` attribute for email is set to `email` and not `text` (so the tests will fail if user attempts to send some random text in email field instead of their actual email address) or if `required` attribute has been used on all the necessary fields (like name or email) before the user attempts to submit his details using the form.

I believe the focus of this project is on implementing best practices for simple forms which help to easily manage the data you receive from them (on the back end/server side).

**Comment by Tiiso** [comment]
@abhishekakade Thank you for helping me with the misunderstanding.
