### ISSUE TITLE
thala

### ISSUE THREAD

**Issue by premkumarbtech** [freeCodeCamp/testable-projects-fcc#919]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 
 
 
```

**Comment by tbushman** [comment]
@premkumarbtech Hello, please provide some more information about the error you are experiencing. Indicate which test is failing and provide a screenshot, a code sample, or a link to your project.

**Comment by premkumarbtech** [comment]
DEAR SIR,
 THANK YOU ERROR IS CLEAR SIR
https://codepen.io/premkumarbtech/pen/xoaqvw

 REGRADS
PREMKUMAR .M

**Comment by premkumarbtech** [comment]
![image](https://user-images.githubusercontent.com/52044505/60736275-01fea880-9f74-11e9-94ed-fd255f6dfe9d.png)

**Comment by premkumarbtech** [comment]
DEAR SIR,
           HI SIR ONE DOUBT SIR  HOW INSERT THE  IMAGE AND TITLE IN SINGLE
COLUMN?????
     THE IMAGE IS RIGHT SIDE AND TITLE IS ALIGNMENT IN CENTER
 HTML AND CSS  CODES
THANKYOU
 REGRADS
PREMKUMAR M

**Comment by RandellDawson** [comment]
@premkumarbtech These kinds of questions should be asked in [our forum](https://www.freecodecamp.org/forum/) since it is not an actual bug you are reporting.  If members of the forum tell you it is a true bug, that is when you would open an issue.  I am closing this for now.  Please feel free to request it be reopened if you are told there is a bug in the tests.

Thank you for understanding.
