### ISSUE TITLE
landing page 

### ISSUE THREAD

**Issue by EdgarVal** [freeCodeCamp/testable-projects-fcc#929]
#### Issue Description

when i run the test it says im not using a media query & i dont have anything using display: flex style but i have multiples of both. Not sure why its giving me an error

#### Browser Information

* Browser Name, Version:  chrome
* Operating System:  windows 10
* Mobile, Desktop, or Tablet:  mobile

#### Screenshot

![2019-07-14](https://user-images.githubusercontent.com/42103433/61190374-3a774400-a650-11e9-9743-9fae913839da.png)
![2019-07-14 (1)](https://user-images.githubusercontent.com/42103433/61190375-3e0acb00-a650-11e9-8126-caa98664eb37.png)

**Comment by lasjorg** [comment]
Odd, can you post a Codepen with your project for us?

**Comment by RandellDawson** [comment]
@EdgarVal Please only create issues if you have first asked your question on the forum and the users determine it is a bug in the tests.  GitHub issues are only for reporting actual bugs in the curriculum or curriculum tests.  If your problem is determined to be an actual bug with the FCC site, you can request this issue to be reopened.  Make sure to include a link to the forum topic.
