### ISSUE TITLE
The height of the welcome section should be equal to the height of the viewport. test fails

### ISSUE THREAD

**Issue by diomed** [freeCodeCamp/testable-projects-fcc#97]
#### Issue Description
I've done Portfolio challenge.
And even tho I've asked around and looked at example,
to see what I did wrong looks like I did nothing wrong,
yet fcc validator doesn't seem to let me pass.

#### Browser Information
* Browser Name, Version: Google Chrome
* Operating System: Windows 10
* Mobile, Desktop, or Tablet:  Desktop

#### Your Code / Link to Your Pen
http://codepen.io/diomed/pen/EmdMrb
```
 
 
 
```

**Comment by christophherr** [comment]
Hi,
the reason the test fails is the padding on `.box`. 
It adds 80px to the "height" of the element and the test is checking against the viewport height.
@no-stack-dub-sack 
Do you think that extending the error message with something like "Please check if you added padding to `#welcome-section`" would help? 
Or would you allow the "extension" of the viewport height by adding any padding to the test?   
e.g. `document.documentElement.clientHeight + parseInt(window.getComputedStyle(elem, null).getPropertyValue('padding'))*2)`

**Comment by diomed** [comment]
thanks @christophherr

**Comment by no-stack-dub-sack** [comment]
@christophherr Hey thanks for looking into this! 

Yeah, I like the second solution better, have you played around with this at all yet? What if padding is defined with clockwise notation instead? This may affect this solution...

**Comment by christophherr** [comment]
@no-stack-dub-sack  My pleasure.

When I looked at it, I only did some quick console.logs and it picked up padding-top and padding-bottom.
Here's a fork of diomed's pen with padding in clockwise notation and console.logs:
https://codepen.io/c-herr/pen/oWKgzv

If you want, I can run it through my local test suite tomorrow and, if it holds up, submit a PR along the lines of `window.innerHeight + parseInt(window.getComputedStyle(welcome-section, null).getPropertyValue('padding'))*2)`

**Comment by no-stack-dub-sack** [comment]
Hey @christophherr, here's what I mean with clockwise notation: https://codepen.io/no_stack_dub_sack/pen/jmgoNv

Where clockwise notation (or even explicitly written notation, i.e. `padding-bottom`, `padding-top`, etc.), can make a difference with this example is when the top padding is different from the bottom padding. When you compute the style and then parse, you only end up with the first number, and multiplying that by 2 won't give you the right answer any more if the top is different than the bottom). 

Also, see my comment in the CSS - bottom padding only can throw this off as well. And if there's only a bottom padding added, the solution at present would add 0 since the first number when you compute the style is the top padding (it will log 4 numbers in order: `top`, `right`, `bottom`, `left`). 

So you can see there are a few not-so-edgey cases that would throw this off. There could be a way around it, but it would probably be pretty contrived. For example, you can split the string and turn it into an array, take the length, and if it is 3 elements long, you need both the first and the 3rd elements, then add those together and that's your total top+bottom margin. Otherwise, if its less than 3 elements long, than you only need the first element in the array. BUT, this still doesn't solve the problem that if the top padding was explicitly defined, with no bottom padding, than you would needlessly by multiplying by 2 and then the calculation is off again. Yeah, haha, this is kind of tricky - lots of things can throw it off, WHICH, is what makes this project so difficult (the testable projects project, not the portfolio specifically). It is very hard to test every way to implement. i.e., you'll also notice the navbar test is failing - because of the CSS library he's using. 

Ok, this is a rant now. But feel free to play around with this and if you come up with a solution that covers all bases, file a PR, otherwise, perhaps just a note in the test case like you also suggested might be the safer bet...

**Comment by christophherr** [comment]
@no-stack-dub-sack  Yeah, that will get really messy... 
Not to mention what happens when the padding is subtracted from the height with something like `height: calc(100vh - 80px)` 

The different CSS libraries surely make it difficult, especially when they are very opinionated (e.g. Materialize in issue 75). 

I will take a look over the weekend.
At the moment, I am thinking a failing test with a note would be better because the criteria state it should be viewport height and it gives them an idea what might be the problem.

**Comment by no-stack-dub-sack** [comment]
@christophherr Yeah, that sounds good, and your right - it does let them know (if they are reading carefully) that the height is not as expected. So that's fair.

**Comment by tchaffee** [comment]
This is actually due to [a documented bug with Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=672457). In short, executing `getBoundingClientRect()` after the `window.scroll(0,500)` with CSS `position:sticky` will give the wrong values. We can work around this in the test but using a `setTimeout` to yield to the browser to finish layout first before executing the `getBoundingClientRect()`. PR in progress.
