### ISSUE TITLE
Product Landing Page test suite incorrectly sees issue with nav-bar.

### ISSUE THREAD

**Issue by mattygersh21** [freeCodeCamp/testable-projects-fcc#973]
#### Issue Description
Product Landing Page test suit incorrectly sees issue with nav-bar. The CSS for the nav-bar element is assigned a fixed position with top or 0. 

#### Browser Information
Using Google Chrome

- Browser Name, Version: Google Chrome version 76.0.3809.132 (Official Build) (64-bit)
- Operating System: Windows 10 Home version 10.0.18362
- Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen
https://codepen.io/matty21/pen/WamZBm

#nav-bar {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  align-items: center;
  background-color: blue;
}
```



```

#### Screenshot
![image](https://user-images.githubusercontent.com/55604190/65359539-6ec42f00-dbc2-11e9-8505-a65ac7bcc4bb.png)

**Comment by tbushman** [comment]
@mattygersh21 The test is detecting siblings of `nav-bar` that scroll with the `header` element because `<header>` is positioned relative to the `<section>`s and therefore scrolls. To account for this, please add `position: fixed;` to   
```  
header {
  margin: 0px 0px;
  align-items: center;
  display: flex;  
  position: fixed;
}  
```   
There may be a better way. And the error message is not totally clear. Will leave this open.

**Comment by mattygersh21** [comment]
Thanks for the explanation and the fix tbushman!
