### ISSUE TITLE
Test failing on technical documentation project 

### ISSUE THREAD

**Issue by raulbarriga** [freeCodeCamp/testable-projects-fcc#977]
#### Issue Description

 Testing the conditions to pass the project test seem unresponsive to pretty much all attempts to get it to pass the project tests. I don’t think the testing source is working properly. Please check. Also, I could not get images of the test issues but they’re pretty much number 4 (the main-section) and 12 (the  Thanks.
#### Browser Information

- Browser Name, Version: Chrome, 77.0.3865.69
- Operating System: IOS 12.4.1
- Mobile, Desktop, or Tablet: tablet

#### Your Code / Link to Your Pen

https://codepen.io/raulbarriga/full/PoYXmpo
```



```

**Comment by RandellDawson** [comment]
@raulbarriga GitHub issues are for reporting bugs in the tests.  The bug is in your HTML.  Please use [our forum](https://www.freecodecamp.org/forum/c/help) when you get stuck on a challenge or project.  If the users on the forum determine your code is fine and should be working, then there might be a bug to report.  I am closing due to the fact the problem stems from a typo in one or more of the `id` attributes of the section headers of your HTML.

**Comment by raulbarriga** [comment]
I tried to make the change that was suggested from the forum but it still didn't accept it. I'll just try the forum again and go from there. Thanks.

**Comment by RandellDawson** [comment]
@raulbarriga Just reply back to your original topic and explain what code you changed and what you are seeing still.  The last user replied to tell you that your typo is in the `id`.
